### ISSUE TITLE
HLS and Progressive Steaming for both iOS & Android.

### ISSUE THREAD

**Issue by mrinaljain** [GeekyAnts/flick-video-player#10]
Video Player does not support HLS and Progressive Steaming for both iOS & Android.
I tried using the HLS file format as an input to the video player but it does not work and shows an error in the view.
Is there a way I can stream HLS URLs in the flick video player
 

`flickManager = FlickManager(
      autoPlay: false,
      autoInitialize: true,
      videoPlayerController: VideoPlayerController.network(
          'https://d2tlhrnhiaq7gn.cloudfront.net/show/main-video/240/${widget.exclusiveDetailObj["mediaList"][0]["hlsSourceLink"]}',
          formatHint: VideoFormat.hls),
    );`

**Comment by ahujaraghav** [comment]
@mrinaljain Are you facing the issue on IOS and Android both?

**Comment by mrinaljain** [comment]
@ahujaraghav  It worked  with  formatHint: VideoFormat.other

**Comment by SmarttersStudio** [comment]
Cant Play m3u8 in IOS
