### ISSUE TITLE
FlickMultiManager error (Android Only)

### ISSUE THREAD

**Issue by wesleytoshio** [GeekyAnts/flick-video-player#102]
I recently came across the problem in my Feed list, when my ListView reaches a certain amount of children, the next videos on the list doesn't work, it only happens on Android
**Short list:**
![image](https://user-images.githubusercontent.com/7057737/124847330-026e1780-df71-11eb-87e3-fcc4f298e9a3.png)
**Bigger list**
![image](https://user-images.githubusercontent.com/7057737/124847386-22054000-df71-11eb-91d6-2e140cb5fbfe.png)

**Comment by geekruchika** [comment]
Please share a video to reproduce it.

**Comment by geekruchika** [comment]
Please try out v0.4.0-dev.2 and let us know if still reproducible. Feel free to open this issue.
