### ISSUE TITLE
When click on fullscreen option simulator and android physical devices changes it's orientation(landscape mode) where on iOS physical devices it's just do full screen instead of changing orientation(landscape mode)

### ISSUE THREAD

**Issue by kishan-entigrity** [GeekyAnts/flick-video-player#104]
version:
flick_video_player: ^0.1.1

When I click on the full-screen button it will change its orientation(landscape view) on the iOS simulator & Android physical devices, but when using the same feature on iOS physical devices on any of the iPhone versions its won't change the orientation, Just stretch the video on fullscreen mode and make it center cropped. Even I have turned on auto rotation on the device it's not changing its orientation.
![1626440105196](https://user-images.githubusercontent.com/56914291/125951206-24fe65eb-e595-4da4-a754-7eb147eeaa38.JPEG)

**Comment by geekruchika** [comment]
@kishan-entigrity 
Please share your code snippet to reproduce? Also can you please try the Flick player example app to check if it can be reproducible?

**Comment by Tomous** [comment]
您好，请问一下这个问题怎么解决的啊，我在iPhone上也遇到了
