### ISSUE TITLE
How to use FlickCurrentPosition

### ISSUE THREAD

**Issue by ankur874** [GeekyAnts/flick-video-player#107]
FlickVideoPlayer(
          flickManager: flickManager,
        ),
FlickCurrentPosition()

I am doing thid

**Comment by geekruchika** [comment]
https://github.com/GeekyAnts/flick-video-player/issues/106

**Comment by ankur874** [comment]
Maam please explain i need it urgent,its a widget but its now showing the video time.
class videoPlayer extends StatefulWidget {
  @override
  _videoPlayerState createState() => _videoPlayerState();
}

class _videoPlayerState extends State<videoPlayer> {
  late FlickManager flickManager;
   Key k=new Key('ankur');
  @override
  void initState() {
    super.initState();
    flickManager = FlickManager(
        autoPlay: false,
        videoPlayerController: VideoPlayerController.network(
            'https://firebasestorage.googleapis.com/v0/b/videoscroller.appspot.com/o/video.mp4?alt=media&token=6af379bb-80e5-4b85-ad04-eed1577440ea'));
  }


  @override
  void dispose() {
    
    super.dispose();
    flickManager.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        FlickVideoPlayer(
          flickManager: flickManager,
        ),
        FlickCurrentPosition()
        
        
      ],
    );
  }
}

**Comment by ahujaraghav** [comment]
@ankur874 please refer to examples or refer [here](https://geekyants.com/blog/creating-a-customisable-video-player-in-flutter-283)

**Comment by geekruchika** [comment]
@ankur874 Hope it's clear. Closing this issue.

**Comment by ankur874** [comment]
Maam sorry...this package is awesome but still i am confused how to get current position of a video.How to use that widget "FlickCurrentPosition".I am using it directly and it showing error.
error:-
Error: Could not find the correct Provider<FlickVideoManager> above this FlickCurrentPosition Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that FlickCurrentPosition is under your MultiProvider/Provider<FlickVideoManager>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),

**Comment by geekruchika** [comment]
That widget is for UI to show how much duration the video is played.

**Comment by geekruchika** [comment]
Your video manager will be able to give you the current position of video.
videoManager.videoPlayerValue?.position.

**Comment by ankur874** [comment]
thanks i got this..but last doubt it's showing undefined name provider?

**Comment by ankur874** [comment]
thanks a lot maam but please last doubt , where to write this code
i am getting this error.Do i have to write this code just below build of my class
error-------------------
rror: Could not find the correct Provider<FlickVideoManager> above this videoPlayer Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:
