### ISSUE TITLE
Does it support subtitles?

### ISSUE THREAD

**Issue by alakreasi** [GeekyAnts/flick-video-player#11]
Does it support subtitles?

thank you

**Comment by alakreasi** [comment]
Hi, how do I set the start at 00:01:00?
I tried this but failed

> `Duration duration = Duration(hours: 0, minutes: 1, seconds: 0, milliseconds: 0);
> flickManager.flickControlManager.seekTo(duration);`

> Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter '_duration' was called on null.
Receiver: null
Tried calling: _duration)

thank you

**Comment by ahujaraghav** [comment]
@alakreasi We do not support subtitles yet.

**Comment by ahujaraghav** [comment]
@alakreasi To start the video at specific duration please try this.

` void initState() {
    super.initState();
    flickManager = FlickManager(
      videoPlayerController:
          VideoPlayerController.network(url),
    );
    flickManager.flickVideoManager.addListener(_startVideoListener);
  }

  void _startVideoListener() {
    if (flickManager.flickVideoManager.isVideoInitialized) {
      flickManager.flickControlManager.seekTo(Duration(minutes: 1));
      flickManager.flickVideoManager.removeListener(_startVideoListener);
    }
  }`

You were getting the above error because seekTo function was called before the video is initialised.

**Comment by ahujaraghav** [comment]
@alakreasi To start the video at specific duration please try this.
```
void initState() {
super.initState();
flickManager = FlickManager(
videoPlayerController:
VideoPlayerController.network(url),
);
flickManager.flickVideoManager.addListener(_startVideoListener);
}

void _startVideoListener() {
if (flickManager.flickVideoManager.isVideoInitialized) {
flickManager.flickControlManager.seekTo(Duration(minutes: 1));
flickManager.flickVideoManager.removeListener(_startVideoListener);
}
}
```

You were getting the above error because seekTo function was called before the video is initialised.
