### ISSUE TITLE
FlickVideoWithControls -> FlickAutoHideChild destroys and recreates widget on show/hide

### ISSUE THREAD

**Issue by pintalubaf** [GeekyAnts/flick-video-player#110]
Hello! Thank you for such a great package.

If I create my own controls and have a widget that does network calls and retrieves data, FlickAutoHideChild is destroying and recreating the widget when it hides and shows the controls.

Is there a way to keep this widget alive? just hide/show it without destroying it? I tried with AutomaticKeepAliveMixin in it but that didn't help.

Thanks.

**Comment by pintalubaf** [comment]
For everyone having this issue, I made a CustomFlickAutoHideChild changing the AnimatedSwitcher to an AnimatedOpacity widget.

`import 'package:flick_video_player/flick_video_player.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

/// AutoHide child according to timeout managed by [FlickDisplayManager].
///
/// Hides the child with [FadeAnimation].
class CustomFlickAutoHideChild extends StatelessWidget {
  const CustomFlickAutoHideChild({
    Key key,
    @required this.child,
    this.autoHide = true,
    this.showIfVideoNotInitialized = true,
  }) : super(key: key);
  final Widget child;
  final bool autoHide;

  /// Show the child if video is not initialized.
  final bool showIfVideoNotInitialized;

  @override
  Widget build(BuildContext context) {
    FlickDisplayManager displayManager =
        Provider.of<FlickDisplayManager>(context);
    FlickVideoManager videoManager = Provider.of<FlickVideoManager>(context);

    return (!videoManager.isVideoInitialized && !showIfVideoNotInitialized)
        ? Container()
        : autoHide
            ? AnimatedOpacity(
                opacity: (displayManager.showPlayerControls) ? 1.0 : 0.0,
                duration: Duration(milliseconds: 300),
                child: child,
              )
            : child;
  }
}
`

Hope this helps you!

**Comment by geekruchika** [comment]
Hey @pintalubaf 
Thanks for the solution. It totally depends on the use-case you are having.

**Comment by geekruchika** [comment]
Feel free to open this issue.
