### ISSUE TITLE
video aspect ration not display properly

### ISSUE THREAD

**Issue by RameshKumar050190** [GeekyAnts/flick-video-player#118]
https://d1wdlxthirotoy.cloudfront.net/aab64d56-7846-409f-b47f-06fb2938de58/abd3b1df-a666-41a9-8369-2bbc03791a8a/a749e3a3-377f-43db-aed9-34d00b0d5874mov?Expires=1629378207&Signature=abp0JYG1PmtQXjH2kaA~S2eEu4SH6~mrRBa-6VdoynN1~d-Q9P5doRc~W16kQ2e1mHn3gJUg6LJ28d~~eaZozl3R4vBtkHDIPZvomiEpv2vMemrE1fciNDS58kenarSaJIyqBQ1PJ7c9M2PzfKwXRO6kDZk~tzZPQBWcqJCIZwkppbFBpMCjnR0slmby5zFvfo5UtKXG6OxV8AZAEPXk2LMJcmaNMuGah8rQJcHO0y45AZ17K3o9FmicHLTit2R1PSxf2LqpijxqO7oi-LGRJpu6IVxBfyxD13dn78G1ldikLU-RH1UB~f-18SVq0xrroBrO46ualGr9NU8dMg6itg__&Key-Pair-Id=KRVGDZNHIDR6A

this is video url
not displaying properly

its working fine in android 

![simulator_screenshot_F7F065AB-81A5-4A94-A34E-06DC1A034F8E](https://user-images.githubusercontent.com/83966587/128467720-7f576709-7da9-4fbb-8a3e-809ddcf24690.png)

**Comment by RameshKumar050190** [comment]
original code:

- (CGAffineTransform)fixTransform:(AVAssetTrack*)videoTrack {
  CGAffineTransform transform = videoTrack.preferredTransform;
  // TODO(@recastrodiaz): why do we need to do this? Why is the preferredTransform incorrect?
  // At least 2 user videos show a black screen when in portrait mode if we directly use the
  // videoTrack.preferredTransform Setting tx to the height of the video instead of 0, properly
  // displays the video https://github.com/flutter/flutter/issues/17606#issuecomment-413473181
  if (transform.tx == 0 && transform.ty == 0) {
    NSInteger rotationDegrees = (NSInteger)round(radiansToDegrees(atan2(transform.b, transform.a)));
    NSLog(@"TX and TY are 0. Rotation: %ld. Natural width,height: %f, %f", (long)rotationDegrees,
          videoTrack.naturalSize.width, videoTrack.naturalSize.height);
    if (rotationDegrees == 90) {
      NSLog(@"Setting transform tx");
      transform.tx = videoTrack.naturalSize.height;
      transform.ty = 0;
    } else if (rotationDegrees == 270) {
      NSLog(@"Setting transform ty");
      transform.tx = 0;
      transform.ty = videoTrack.naturalSize.width;
    }
  }
  return transform;
}
new code

- (CGAffineTransform)fixTransform:(AVAssetTrack*)videoTrack {
  CGAffineTransform transform = videoTrack.preferredTransform;
  // TODO(@recastrodiaz): why do we need to do this? Why is the preferredTransform incorrect?
  // At least 2 user videos show a black screen when in portrait mode if we directly use the
  // videoTrack.preferredTransform Setting tx to the height of the video instead of 0, properly
  // displays the video https://github.com/flutter/flutter/issues/17606#issuecomment-413473181
  NSInteger rotationDegrees = (NSInteger)round(radiansToDegrees(atan2(transform.b, transform.a)));
  NSLog(@"TX and TY are 0. Rotation: %ld. Natural width,height: %f, %f", (long)rotationDegrees,
        videoTrack.naturalSize.width, videoTrack.naturalSize.height);
  if (rotationDegrees == 90) {
    NSLog(@"Setting transform tx");
    transform.tx = videoTrack.naturalSize.height;
    transform.ty = 0;
  } else if (rotationDegrees == 180) {
    transform.tx = videoTrack.naturalSize.width;
    transform.ty = videoTrack.naturalSize.height;
  } else if (rotationDegrees == 270) {
    NSLog(@"Setting transform ty");
    transform.tx = 0;
    transform.ty = videoTrack.naturalSize.width;
  }
  return transform;
}

**Comment by RameshKumar050190** [comment]
its working fine now with these changes

**Comment by ahujaraghav** [comment]
Closing the issue as its resolved.
