### ISSUE TITLE
Plz add Live support for youtube video and speedo meter and quality options as soon as possible

### ISSUE THREAD

**Issue by shailendra-rajpoot** [GeekyAnts/flick-video-player#12]
Plz add Live support for youtube video and speedo meter and quality options as soon as possible

**Comment by shailendra-rajpoot** [comment]
bro i m not getting you plz share code for Live support for youtube video and speedo meter and quality options

**Comment by ahujaraghav** [comment]
@shailendra-rajpoot Live youtube video is not supported yet.
