### ISSUE TITLE
Video Showing white screen in Release mode

### ISSUE THREAD

**Issue by sanchitmit26** [GeekyAnts/flick-video-player#120]
Video in list  playing good  in Development mode, But when I have created Released APK, Video showing white screen on video

**Comment by geekruchika** [comment]
Hi @sanchitmit26 
I tried flutter run --release and it's working fine. 
Can you please elaborate the issue?

**Comment by sanchitmit26** [comment]
Hello 
Thanks for reply

I just downloaded sample and its feedplayer listview working too good in debug mode but when I create signed apk and install in Android device then in feedplayer listview, white screen showing in video


![Screenshot_2021-08-18-19-14-56-92_082aea295e0e2b19157fadadca43d2cc](https://user-images.githubusercontent.com/89126601/129910119-a8d7e9e9-f672-4fd1-9807-dfb2eef21efe.jpg)
![Screenshot_2021-08-18-19-19-44-55_082aea295e0e2b19157fadadca43d2cc](https://user-images.githubusercontent.com/89126601/129910134-4d6f67c2-28da-4d80-986a-a8e2629df7a6.jpg)

**Comment by sanchitmit26** [comment]
Waiting for help...please have a look on above issue

**Comment by geekruchika** [comment]
How are you creating apk? Can you please share apk too?

**Comment by sanchitmit26** [comment]
> Did you manipulated the example app UI? Can you please share apk too?
> Please try to build apk directly from Master branch and try it.

Where I can share APK with you mam. my email id is sanchitmit26@gmail.com

**Comment by geekruchika** [comment]
@sanchitmit26 Seema like you have changed some UI for the apk. E.g control bar is at the top and in our example app, it's at the bottom. You must be getting some exceptions at the terminal for sure. Please try to track that.

**Comment by geekruchika** [comment]
> > Did you manipulated the example app UI? Can you please share apk too?
> > Please try to build apk directly from Master branch and try it.
> 
> Where I can share APK with you mam. my email id is [sanchitmit26@gmail.com](mailto:sanchitmit26@gmail.com)

@sanchitmit26 Seema like you have changed some UI for the apk. E.g control bar is at the top and in our example app, it's at the bottom. You must be getting some exceptions at the terminal for sure. Please try to track that.

**Comment by geekruchika** [comment]
@sanchitmit26 Let me know if we can close this issue.

**Comment by geekruchika** [comment]
Feel free to open if required. Thanks.

**Comment by vikaspAlgoworks** [comment]
Any update on this ?
