### ISSUE TITLE
can't show dialog / modal when fullscreen

### ISSUE THREAD

**Issue by callmejm** [GeekyAnts/flick-video-player#125]
I wish to show a dialog / modal when press a button in fullscreen, but it wont appear inside fullscreen, it show outside of fullscreen

     showGeneralDialog(
        barrierLabel: "Barrier",
        barrierDismissible: true,
        barrierColor: Colors.black.withOpacity(0.5),
        transitionDuration: Duration(milliseconds: 300),
        context: context,
        useRootNavigator: false,
        pageBuilder: (context, animation1, animation2) {
          return Align(
            alignment: (Alignment.centerRight),
            child: Container(
              height: double.infinity,
              width: 300,
              decoration: BoxDecoration(
                color: Colors.white,
              ),
            ),
          );
        },
        transitionBuilder: (context, animation1, animation2, child) {
          return SlideTransition(
            position:
                Tween(begin: Offset(1, 0), end: Offset(0, 0))
                    .animate(animation1),
            child: child,
          );
        },
      );

https://user-images.githubusercontent.com/6957533/131345938-0f782a3c-1b76-4bf4-812e-a9a202a3abee.mp4

**Comment by knowsach** [comment]
@callmejm you can try out this package ([overlay_dialog](https://pub.dev/packages/overlay_dialog) ) to show dialogs on overlay.

**Comment by ansh-les** [comment]
@callmejm Did you manage to resolve this? I'm facing the exact same problem in my project.

**Comment by demirdemirel** [comment]
I have a similar issue with that library, I want to have bottom sheet modal for presenting comments etc. in front of the video player. Any one has any solutions about it ?
