### ISSUE TITLE
orientation issue

### ISSUE THREAD

**Issue by callmejm** [GeekyAnts/flick-video-player#129]
I when toggle fullscreen landscape, it begin with landscape then immediately fallback to portrait fullscreen 

https://user-images.githubusercontent.com/6957533/132488751-9c20ecb1-3cff-4e97-8407-d1b20968a59f.mp4

**Comment by TejasShukalPlutustec** [comment]
Did you find the solution of this issue?

**Comment by geekruchika** [comment]
Can you please provide code snippet? I have tried example app. It's working fine.

**Comment by geekruchika** [comment]
> I when toggle fullscreen landscape, it begin with landscape then immediately fallback to portrait fullscreen
> 
>  bandicam.2021-09-08.17-56-25-423.mp4

Hi @callmejm
Can you please provide code snippet? I have tried example app. It's working fine.

**Comment by callmejm** [comment]
I found the issue because , full screen control I using `HookWidget` , meaning `flick-video-player` `initState` might call twice or more, when `initState` default DeviceOrientation are portrait , so when trying to fullscreen state reinitialize
