### ISSUE TITLE
Not compatible with provider ^6.0.0

### ISSUE THREAD

**Issue by lulumeimei** [GeekyAnts/flick-video-player#133]
Because no versions of flick_video_player match >0.3.1 <0.4.0 and flick_video_player 0.3.1 depends on provider ^5.0.0, flick_video_player ^0.3.1 requires provider ^5.0.0.
And because flutter_bloc >=7.2.0 depends on provider ^6.0.0, flick_video_player ^0.3.1 is incompatible with flutter_bloc >=7.2.0.

**Comment by intraector** [comment]
Same here

**Comment by geekruchika** [comment]
Soon will be upgrading packages.

**Comment by geekruchika** [comment]
Please try the updated version: https://pub.dev/packages/flick_video_player/versions/0.4.0-dev.4

Provider updated to the latest.
