### ISSUE TITLE
both provider ^6.0.1 and flick_video_player ^0.3.1, version solving failed

### ISSUE THREAD

**Issue by dryasbk** [GeekyAnts/flick-video-player#139]
Because flick_video_player 0.3.1 depends on provider ^5.0.0 and no versions of flick_video_player match >0.3.1 <0.4.0, flick_video_player ^0.3.1 requires provider ^5.0.0.
So, because my app depends on both provider ^6.0.1 and flick_video_player ^0.3.1, version solving failed.
pub get failed (1; So, because my app depends on both provider ^6.0.1 and flick_video_player ^0.3.1, version solving failed.)

**Comment by dryasbk** [comment]
if I use   flick_video_player: ^0.3.1 it gives the error
when I did pub outdated it changed to
flick_video_player: ^0.4.0-dev.4
and worked???

**Comment by geekruchika** [comment]
Yes latest version is ^0.4.0-dev.4.
