### ISSUE TITLE
[FEATURE REQUEST] Swipe to dismiss fullscreen video

### ISSUE THREAD

**Issue by NaikSoftware** [GeekyAnts/flick-video-player#142]
When video opened in fullscreen mode (overlay) I want to cancel by swipe. 
Possible solutions:
 - simple gesture detector over player 
 - wrap into SwipeToDismiss if it is possible
 - other variant in comments

**Comment by geekruchika** [comment]
This can be done easily on your app level itself and control video via your video controller.
