### ISSUE TITLE
Fullscreen mode not working when player in "feed"

### ISSUE THREAD

**Issue by NaikSoftware** [GeekyAnts/flick-video-player#143]
I used example "feed" with flick multi manager. All working great, but when I open landscape video in fullscreen then all app rebuilds and item widgets also disposes and inits new. When this occurs foregraund layer stay to use disposed flickmanager and crashes.

**Comment by amanchauhan06** [comment]
This was not reproducible for us sir. Can you please share the code snippet where you were trying to use this.

**Comment by geekruchika** [comment]
Closing this.
