### ISSUE TITLE
Infinite circular progress on IOS 15, even for empty link

### ISSUE THREAD

**Issue by adrianvintu** [GeekyAnts/flick-video-player#145]
I  try to play different videos on iphone v15 and i only get an infinite circular widget.

When I set link = "" I get no error message, only infinite circular widget.

    flickManager = FlickManager(
      //getPlayerControlsTimeout: _getPlayerControlsTimeout,
      //reset variable
      onVideoEnd: onVideoEnd,
      videoPlayerController: VideoPlayerController.network(link),
      autoPlay: pausedPosition == null ? true : false,
    );

Is there a debug flag that could show me that is going on in the background?

**Comment by adrianvintu** [comment]
I have tested the `DefaultPlayer` class using `mock_data.dart` and it seems only `The Valley` is playing.

Device is: iPhone Mini 12 with Software Version 15.1

**Comment by adrianvintu** [comment]
I have tested on Safari and none of the links are played. They show an infinite circle loading.

**Comment by adrianvintu** [comment]
More feedback.
1. Infinite circular progress on IOS 15, even for empty link. The URLs I tried to play in my app contained spaces, so I needed to set `link = Uri.encodeFull("my link");`
No more issue on my videos.
2. The issue about only `The Valley` playing is still on.

**Comment by geekruchika** [comment]
Ok, I will try on iOS 15. 
Any error logs can you please share?

**Comment by adrianvintu** [comment]
Sorry, no logs unfortunately.

**Comment by geekruchika** [comment]
@adrianvintu Please try the latest version with custom hosted URLs and let me know if still exists.

**Comment by adrianvintu** [comment]
@geekruchika what is the latest version and what is "custom hosted URLs"?

**Comment by geekruchika** [comment]
Latest Flick player version.
flick_video_player: ^0.5.0
