### ISSUE TITLE
m3u8 format not playing.

### ISSUE THREAD

**Issue by Gursewak-Uppal** [GeekyAnts/flick-video-player#15]
Live video not played. Please add live video play support.

**Comment by mrinaljain** [comment]
@Gursewak-Uppal 
It worked perfectly after adding this property 
formatHint: VideoFormat.hls

**Comment by Gursewak-Uppal** [comment]
Yes it's working, Thanks

**Comment by yuxingmin** [comment]
try:https://vod2.bdzybf7.com/20220330/T0NA7RYC/index.m3u8
not play
