### ISSUE TITLE
[QUESTION] Remove Fullscreen Button

### ISSUE THREAD

**Issue by ayberkcal** [GeekyAnts/flick-video-player#152]
I would like to remove just fullscreen action button however I could not found any setting about that. Does package support that?

**Comment by IJEENI** [comment]
find flick_full_screen_toggle.dart , return Sizedbox widget instead of GestureDetector.

**Comment by geekruchika** [comment]
No @ayberkcal .
You can fork the package and hide the fullscreen action button.
