### ISSUE TITLE
web 

### ISSUE THREAD

**Issue by changkuanlai** [GeekyAnts/flick-video-player#157]
![3831641869236_ pic_hd](https://user-images.githubusercontent.com/22167353/148873138-4d7ff80b-17e3-4fc8-8dea-cf1953a59584.jpg).
hi 
 When I use web build on windows, this will happen

**Comment by geekruchika** [comment]
Hi @changkuanlai 
Can you please share me the hosted link to verify it?

**Comment by geekruchika** [comment]
Closing this. Feel free to reopen.
