### ISSUE TITLE
How can I get play and pause event

### ISSUE THREAD

**Issue by Ghayyas** [GeekyAnts/flick-video-player#159]
Hello,
I'm using this plugin for the video. I want to call a Dialog when the user clicks on the play button and if he clicks confirms only then the video should play. Otherwise, the video should stop. 

How can I add this kind of functionality?

Thanks!

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by Zeeshan0201** [comment]
any update here?

**Comment by geekruchika** [comment]
This will be an enhancement. Currently, it's behaving like normal players. You can customize it by forking and updating Play button on press.
