### ISSUE TITLE
how to add Listener

### ISSUE THREAD

**Issue by chinu999** [GeekyAnts/flick-video-player#16]
i want to add listener.

flickManager.addListener(() { })

**Comment by ahujaraghav** [comment]
@chinu999 you can add listeners on flickManager.flickVideoManager, flickManager.flickControlManager & flickManager.flickDisplayManager.

**Comment by chinu999** [comment]
is their any way to add value something like this.
    flickManager.flickVideoManager.addListener(() {
      if (flickManager.value.hasError) {
        print(flickManager.value.errorDescription);
      }
      if (flickManager.value.initialized) {}
      if (flickManager.value.isBuffering) {}

    });
