### ISSUE TITLE
Make WillPopScope optional in favour of Swipe to Go back gesture in IOS

### ISSUE THREAD

**Issue by mohdtaha60** [GeekyAnts/flick-video-player#160]
Firstly, Thanks for this amazing library.,
I noticed one issue with FlickVideoPlayer, When implemented in a screen where going back is possible.
The WillPopScope disables the Swipe to go back gesture of IOS, Hence one cannot go back while having video player in screen.
This can be resolved by making onWillPop optional for FullScreen
i.e.

    return WillPopScope(
      onWillPop: _overlayEntry != null
          ? () {
              flickManager.flickControlManager!.exitFullscreen();
              return Future.value(false);
            }
          : null,
      child: FlickManagerBuilder(
        flickManager: flickManager,
        child: widget.flickVideoWithControls,
      ),
    );

**Comment by geekruchika** [comment]
Hi @mohdtaha60 
Thanks for pointing this out. PR is highly appreciated. We can keep keep a track for your contribution.

**Comment by mohdtaha60** [comment]
Added PR #161

**Comment by geekruchika** [comment]
It's merged.
