### ISSUE TITLE
Screen Keeps Going to Sleep

### ISSUE THREAD

**Issue by paulsarknas1** [GeekyAnts/flick-video-player#167]
Hello, no matter what I do, when the video is playing, the screen keeps going to sleep.  Please advise on how to keep the screen "on" when playing video in full screen.

Thanks!
Paul

**Comment by geekruchika** [comment]
Please share the code snippet. Examples are working properly.

**Comment by geekruchika** [comment]
Closing this PR. Feel free to open if issue still persists.
