### ISSUE TITLE
Plz add Live support for youtube video and speedo meter and quality options as soon as possible

### ISSUE THREAD

**Issue by shailendra-rajpoot** [GeekyAnts/flick-video-player#17]
Plz add Live support for youtube video and speedo meter and quality options as soon as possible plz share code.

**Comment by ahujaraghav** [comment]
Same as #12, closing the issue.

**Comment by shailendra-rajpoot** [comment]
Plz add Live support for youtube video and speedo meter and quality options as soon as possible
plz sir tell me how much time will it take i m waiting your rply ???
