### ISSUE TITLE
mute video when loaded

### ISSUE THREAD

**Issue by Alade5673** [GeekyAnts/flick-video-player#170]
please how can I mute te video when loaded, until users taps on it before it unmutes?

How can I make the videos autoplay?

**Comment by atishpaul** [comment]
Hi.
The default setting is already set to Autoplay. So, You do not need to set it. and if you want to mute on the start of the video, Use this:

```
FlickManager? flickManager;

@override
  void initState() {
    super.initState();
    flickManager = FlickManager(
      videoPlayerController: VideoPlayerController.network("https://assets.mixkit.co/videos/preview/mixkit-spinning-around-the-earth-29351-large.mp4"),
    );
    flickManager!.flickControlManager!.mute();
  }
```

**Comment by geekruchika** [comment]
Hope this worked else feel free to open this issue.

@atishpaul Thanks.
