### ISSUE TITLE
youtube video from url

### ISSUE THREAD

**Issue by Ashish-Raturi** [GeekyAnts/flick-video-player#172]
First of all thanks men, I like your plugins.
I have a request can you add code, for getting videos from youtube URLs.

example url = 
https://www.youtube.com/watch?v=IB7b3S3W8RI

**Comment by ihorkozar** [comment]
@Ashish-Raturi Did you find a solution?

**Comment by Ashish-Raturi** [comment]
@ihorkozar use different plugin https://pub.dev/packages/youtube_player_flutter
