### ISSUE TITLE
Animation Aspect Ratio

### ISSUE THREAD

**Issue by chinu999** [GeekyAnts/flick-video-player#18]
In animation video player to fit in full screen Portrait mode it cut some video sides.
is their any way i can do it with default video player or can you please tell us what is the aspect ratio .

**Comment by ahujaraghav** [comment]
@chinu999 you can use `videoFit` property in `FlickVideoWithControls`. Check this [example](https://github.com/GeekyAnts/flick-video-player/blob/example/custom-fit-player/example/lib/custom_fit_player/custom_fit_player.dart).
