### ISSUE TITLE
Does not play the video on iphone

### ISSUE THREAD

**Issue by EduardEddy** [GeekyAnts/flick-video-player#183]
I uses flick_video_player but on iphone only sounds the video but does not play that

**Comment by amanchauhan06** [comment]
https://user-images.githubusercontent.com/48275253/177704527-1f34c5f8-27f9-4896-94e5-ef879409424a.mp4

It seems to work fine on iOS in the example. Please refer the video. 
If the issue persist please share the code snippet so that we can have a look at it.

**Comment by geekruchika** [comment]
Closing this as it can't be reproducible.
