### ISSUE TITLE
Video end callback

### ISSUE THREAD

**Issue by Inihood1** [GeekyAnts/flick-video-player#185]
Please add video callback to detect when video has ended

**Comment by rohitprajapatii** [comment]
`
  /// Video end callback, change the video in this callback.
  Function? onVideoEnd;
`
There is a video end callback named 'onVideoEnd' in the FlickManager.

**Comment by Inihood1** [comment]
Seen. Thank you. I have another question which is not related to this topic but is there a way I can pre-burfer videos in a listview builder before they are shown on screen?

**Comment by geekruchika** [comment]
Currently, we don't have caching setup. So it's not supported yet.
