### ISSUE TITLE
Feed player + controls

### ISSUE THREAD

**Issue by RoyalCoder88** [GeekyAnts/flick-video-player#187]
Hi friends, 

I'm using Flick video player for feed purposes but I want to show also controls on the video player, how can I achieve this, thanks in advance!

**Comment by amanchauhan06** [comment]
In "**FlickMultiPlayer**" you must be giving controls like this (on line no. 75 to 78 and 86):
![flickmultiplayer](https://user-images.githubusercontent.com/48275253/183833221-f79870c2-bc92-4aa7-9733-b6d1e05caab5.png)
In **FeedPlayerPortraitControls** you can give additional controls of your choice as mentioned in the above comment.

**Comment by RoyalCoder88** [comment]
Hi @amanchauhan06 I figure out I found a solution from the their example and with your help ;)
