### ISSUE TITLE
Feature request : Customized FlickPlayToggle

### ISSUE THREAD

**Issue by atishpaul** [GeekyAnts/flick-video-player#188]
Hi, thanks for this awesome video player, In addition to this i think we should get customized `FlickPlayToggle`.

**Comment by amanchauhan06** [comment]
Hello sir,

FlickPlayToggle is completely customisable you can give the widget of your choice to anything as you can see in the attached code snippet

![flickPlayToggle](https://user-images.githubusercontent.com/48275253/183656632-2f64d312-6f0a-4574-9d10-7adec9f5f2a4.png)
