### ISSUE TITLE
Unable to change color for buffer circularprogressIndicator

### ISSUE THREAD

**Issue by theAkshay60** [GeekyAnts/flick-video-player#189]
Should be able to change the color for buffer circularprogress indicator

**Comment by amanchauhan06** [comment]
@theAkshay60  
![code](https://user-images.githubusercontent.com/48275253/183654381-4e35efe3-3556-43a9-8131-efe0dc569747.png)

You can give **bufferingChild** as a parameter in  **FlickVideoBuffer** and you can give any widget you want as a buffer widget.

**Comment by alihabbash** [comment]
You would add a `playerLoadingFallback` to be a `CircularProgressIndicator` with the custom color you want as follow:

```
FlickVideoPlayer(
            flickManager: flickManager,
            flickVideoWithControls: const FlickVideoWithControls(
              controls: CustomOrientationControls(),
              **playerLoadingFallback: Center(
                child: CircularProgressIndicator(
                  color: Color(0xFFE3E935),
                ),
              ),**
              videoFit: BoxFit.fitWidth,
            ),
),
```
