### ISSUE TITLE
Video feed performance.

### ISSUE THREAD

**Issue by radi-cho** [GeekyAnts/flick-video-player#19]
Hello. We are attempting to use the flick video player in a big social media like product. Our main concern is the performance of the plugin and the speed of video loading in a big feed of videos. As maintainers we would love to hear from a first party:

- Should we worry about memory issues when having a big feed of videos (talking 30-100 videos).
- What are the best practises for speed optimization and performance boost? What are some things we should be careful about to not face big speed/memory problems?
- - For example how to ensure the first videos in a feed load first and the rest load after the first ones are already playing. Also how to ensure that **not** all videos are loading simultaneously, because this would cause caching issues, network overload and dropped frames in the already playing videos;
- Any additional guidelines on how to most efficiently implement a big feed of videos.

Thanks

**Comment by ahujaraghav** [comment]
@radi-cho Flick video player helps you create custom set of controls and players over official [video_player](https://pub.dev/packages/video_player) by Flutter. The official video player plugin currently do not support video caching and as soon as the widget is disposed all the resources used by that widget are released. The best way to do this is to create widgets on demand by using solutions like ListView.builder which will auto load and dispose widgets based on what user is currently seeing on screen. Avoid using ListView which will render all the items together and use lot of resource. Hope this helps.

**Comment by radi-cho** [comment]
Thanks. Closing as answered.
If we have additional questions we will reach out to you again.

All the best!
Radostin Cholakov

**Comment by leonalonso** [comment]
I have the same problem, I have implemented it perfectly in my social app but due to this slowness I had to remove this package, returning to the classic cahed video player which will not be perfect but solves these problems, very important in a social app.

**Comment by gulmensedat** [comment]
> I have the same problem, I have implemented it perfectly in my social app but due to this slowness I had to remove this package, returning to the classic cahed video player which will not be perfect but solves these problems, very important in a social app.

Hello, the video is being reloaded and reset, I couldn't find a solution for this. cached video player did not work for me. How do you solve it?

**Comment by JunaidKhan448** [comment]
facing same issue like @gulmensedat . Can any one provide solution for implementing videos with cache like in insta feed.
