### ISSUE TITLE
How do i pass dynamic start time  when the  video initializes ?

### ISSUE THREAD

**Issue by mrinaljain** [GeekyAnts/flick-video-player#20]
I'm now developing Video player in Flutter and using Flick package 
The video will be streamed with m3u8 format to the Flutter App. I would like to let the user to choose Video Quality (720p, 480p, etc.) like Youtube.
Since Flutter's video_player is based on ExoPlayer for Android under the hood, I know that ExoPlayer supports choosing Video Quality by the users.

Whenever User selects the new video quality from a list I want the new video to be played from exactly same time where the last video was left .

**Comment by ahujaraghav** [comment]
@mrinaljain Flick does not support this feature yet, you will have to manually handle this. You can set autoPlay to false and seek the video manually.

**Comment by adrianvintu** [comment]
@mrinaljain pretty cool what you are saying, do you have some links to show how we can allow the user to choose video quality?

@ahujaraghav how can we know when the video has loaded, so that we can start seeking and playing?

**Comment by vipinnegi90** [comment]
try this: 

``` 
if (flickManager.flickVideoManager.isVideoInitialized) {
      if(widget.resumeDuration != 0 && hasResumed == false){
            flickManager.flickControlManager.seekTo(Duration(seconds: widget.resumeDuration));
            hasResumed = true;
      }
}

works for me
