### ISSUE TITLE
In Web after clicking once clicked on full screen in video  player screen and then clicked on compact view screen button  turns video black after going back to compact view screen.

### ISSUE THREAD

**Issue by mahboobahmed6577** [GeekyAnts/flick-video-player#205]
Hi, I'm working on Flutter Web for a project and integrated Flick video player. Everything seems to work fine except after clicking on full screen in video  player screen turns black after going back to compact view screen. If you go again to Full screen it works fine. Any solution for this issue ? 
Thanks

**Comment by NaveenSTAGE** [comment]
i am also facing the same issue

**Comment by mehroze-zaidi** [comment]
Facing the same issue.
@mahboobahmed6577  did you find any workaround?

**Comment by mahboobahmed6577** [comment]
@mehroze-zaidi  still nothing. I had to disable full screen mode for now.

**Comment by mehroze-zaidi** [comment]
@mahboobahmed6577 okay!

**Comment by geekruchika** [comment]
Fixed in flick_video_player 0.7.0 version.
