### ISSUE TITLE
Muted video 

### ISSUE THREAD

**Issue by JakubKostrzewsky** [GeekyAnts/flick-video-player#208]
Hi, I have a little problem. All videos that I run with your package are muted at the start.
Can someone help me 🙏 🙏 ?

I use code from this example:
https://github.com/GeekyAnts/flick-video-player/blob/master/example/lib/web_video_player/web_video_player.dart

**Comment by gigi** [comment]
As temporary solution you can use this code:

```dart
      onVisibilityChanged: (visibility) {
        if (visibility.visibleFraction == 0 && mounted) {
          flickManager.flickControlManager?.autoPause();
        } else if (visibility.visibleFraction == 1) {
          flickManager.flickControlManager?.autoResume();
          flickManager.flickControlManager!.unmute();
        }
      },
```

**Comment by geekruchika** [comment]
By default, I have kept video muted on the Flick Manager. You can use FlickManager to pass all the inital setup required.

FlickControlManager is responsible to perform action on the video such as play, mute, seek, toggle full-screen etc.
