### ISSUE TITLE
Error while using fullscreen landscape mode in listView.builder

### ISSUE THREAD

**Issue by danielwalczak** [GeekyAnts/flick-video-player#21]
When I have fullscreen video player launched within listView.builder its stop working, probably because when device is rotated list item is being removed from the list, same as video player is being disposed. It working perfectly when video player its displayed outside of the listView.builder.

Any idea how solve this issue ?

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Container(constraints: BoxConstraints(w=450.0, h=800.0)):
A VideoPlayerController was used after being disposed.
```

Other question is it possible to support `slide down` gesture to dismiss fullscreen mode? Would it require to implement fullscreen via `Navigator` ?

**Comment by ahujaraghav** [comment]
@danielwalczak Can you share some code samples to help you better on this.
