### ISSUE TITLE
BottomSheet and dialog in full screen video

### ISSUE THREAD

**Issue by ChiragYogi** [GeekyAnts/flick-video-player#212]
Hi,

i am using flick with custom controller in  my project and so far it has been very helpful.
right now i am stuck at loading a bottom sheet like YouTube while  video  play  in landscape view.

bottom sheet does open but only when video player view goes from landscape to portrait.

I have tried few possible solution but they aren't working as of now.

also is is there any way to play video with different quality like 360p,480p,1080p with flick video player.

any help would be appreciated.

Thank You.

**Comment by techuzRaju** [comment]
@ChiragYogi have you got any solution for this?

**Comment by ChiragYogi** [comment]
hello @techuzRaju,

After some R & D on flick video player source code i have found that for landscape orientation flick use OverlayEntry to draw new widget on current screen for full screen video.
i have used similar approach in my project with OverlayEntry and some animation.

This blog of logrocket will help you understand OverlayEntry better.
https://blog.logrocket.com/complete-guide-implementing-overlays-flutter/

Thank you
