### ISSUE TITLE
Mute video and exit full screen error black screen on the web

### ISSUE THREAD

**Issue by SangND2000** [GeekyAnts/flick-video-player#218]
- Hi, I have a little problem. All videos that I run with your package are muted at the start.
- When exiting full screen, I get a black screen and sometimes I can't watch the video anymore
Can someone help me 🙏 🙏 ?

I use code from this example:
https://github.com/GeekyAnts/flick-video-player/blob/master/example/lib/web_video_player/web_video_player.dart

**Comment by andrezanna** [comment]
I have the same exact issues, how can we solve? Thanks

**Comment by NaveenSTAGE** [comment]
I am also facing the same issue, video muted on initialised

and 

Video went blank but audio is getting played after exiting the fullscreen

**Comment by SangND2000** [comment]
> I have the same exact issues, how can we solve? Thanks

**Comment by SangND2000** [comment]
> I've created a pull request which skips both issues, not a real solution but it works

In your PR
I tried this way it works

`  void exitFullscreen() {
    if (kIsWeb) {
      // trigger controllers again after exiting full screen in web
      Duration position =
          _flickManager.flickVideoManager!.videoPlayerValue!.position;
      _flickManager.flickVideoManager!.videoPlayerController!.initialize().then(
            (_) => Future.delayed(
              const Duration(milliseconds: 300),
              () => _flickManager.flickControlManager!.seekTo(position),
            ),
          );
      togglePlay();
      _notify();
    }
    _isFullscreen = false;
    _flickManager._handleToggleFullscreen();
    _notify();
  }`

**Comment by SangND2000** [comment]
please clone the library and fix it my way, it will work @NaveenSTAGE
