### ISSUE TITLE
Android portrait fullscreen mode issue

### ISSUE THREAD

**Issue by danielwalczak** [GeekyAnts/flick-video-player#22]
On android while the player is in fullscreen mode, the bottom navigation bar is not fully hidden, while in the landscape mode everything looks fine.

<img width="483" alt="Screen Shot 2020-08-13 at 9 49 53 AM" src="https://user-images.githubusercontent.com/3720039/90163297-c32c4c00-dd4a-11ea-8ea1-212a656f3376.png">

<img width="433" alt="Screen Shot 2020-08-13 at 9 51 56 AM" src="https://user-images.githubusercontent.com/3720039/90163194-a09a3300-dd4a-11ea-999f-66b68945c025.png">

**Comment by ahujaraghav** [comment]
@danielwalczak set systemUIOverlay parameter to empty array in FlickVideoPlayer.

**Comment by danielwalczak** [comment]
in this configuration issue still exists, only in landscape mode there its not.

```
FlickVideoPlayer(
        flickManager: flickManager,
        wakelockEnabled: false,
        wakelockEnabledFullscreen: true,
        systemUIOverlayFullscreen: [],
        systemUIOverlay: [],
        preferredDeviceOrientationFullscreen: [
          DeviceOrientation.portraitUp,
        ],
)
```
<img width="421" alt="Screen Shot 2020-09-07 at 5 40 54 PM" src="https://user-images.githubusercontent.com/3720039/92417731-946e7f00-f118-11ea-8220-359edb9481d7.png">

**Comment by sahilgeekyants** [comment]
@danielwalczak 
I tested this issue (with flutter version 2.0.4) in different iOS and Android devices. I didn’t faced any such issue of bottom navigation bar hiding some portion screen in full screen mode. I used the exact same configuration given in the above comment. 
![Android_screen](https://user-images.githubusercontent.com/60209052/117448455-67e75d00-af5c-11eb-9027-ef769bbbbedd.png)
![Android_full_screen](https://user-images.githubusercontent.com/60209052/117448439-628a1280-af5c-11eb-8784-e479f0db757c.png)
![ios_screen](https://user-images.githubusercontent.com/60209052/117448461-69b12080-af5c-11eb-808d-9af278daf17e.png)
![ios_full_screen](https://user-images.githubusercontent.com/60209052/117448459-69188a00-af5c-11eb-963e-0d2e8ab79587.png)

**Comment by geekruchika** [comment]
Please try updated plugin.
