### ISSUE TITLE
在ios上这个m3u8视频链接无法播放，安卓是正常的，https://vod2.bdzybf7.com/20220330/T0NA7RYC/index.m3u8

### ISSUE THREAD

**Issue by dary123** [GeekyAnts/flick-video-player#225]
在ios上这个m3u8视频链接无法播放，安卓是正常的，https://vod2.bdzybf7.com/20220330/T0NA7RYC/index.m3u8

**Comment by geekruchika** [comment]
This is very specific to this file. Else m3u8 format is supported by the player.
