### ISSUE TITLE
Resolving dependencies with wakelock

### ISSUE THREAD

**Issue by RoyalCoder88** [GeekyAnts/flick-video-player#226]
Hi thanks for your great package please update the dependencies:

`
    Because no versions of flick_video_player match >0.5.0 <0.6.0 and flick_video_player 0.5.0 depends on wakelock ^0.6.0, flick_video_player ^0.5.0 requires wakelock ^0.6.0.
(1) So, because wakelock >=0.5.6 depends on wakelock_windows ^0.2.0, flick_video_player ^0.5.0 requires wakelock_windows ^0.2.0.

    Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
    And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
    And because flick_video_player ^0.5.0 requires wakelock_windows ^0.2.0 (1), flick_video_player ^0.5.0 requires win32 ^2.0.0 or ^3.0.0.
    And because share_plus >=7.0.0 depends on win32 ^4.0.0, flick_video_player ^0.5.0 is incompatible with share_plus >=7.0.0.
    So, because myapp depends on both share_plus ^7.0.0 and flick_video_player ^0.5.0, version solving failed.
`

Thanks in advance!

**Comment by sreerajkarippala** [comment]
I am facing same issue any possible solution

**Comment by geekruchika** [comment]
Upgraded package with latest Flutter 3.16

**Comment by 2000calories** [comment]
same issue here
```
Thus, every version of flick_video_player requires win32 ^2.0.0 or ^3.0.0.
And because package_info_plus >=4.0.1 depends on win32 >=4.0.0 <6.0.0, flick_video_player is incompatible with package_info_plus >=4.0.1.
```

**Comment by annd22** [comment]
same issue

**Comment by ngedev** [comment]
Same issue here

`Because flick_video_player 0.7.0 depends on wakelock ^0.6.2 and no versions of wakelock match >0.6.2 <0.7.0, flick_video_player 0.7.0 requires wakelock 0.6.2.
(1) So, because wakelock 0.6.2 depends on wakelock_windows ^0.2.0, flick_video_player 0.7.0 requires wakelock_windows ^0.2.0.

    Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
    And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
    And because flick_video_player 0.7.0 requires wakelock_windows ^0.2.0 (1), flick_video_player 0.7.0 requires win32 ^2.0.0 or ^3.0.0.
    And because package_info_plus >=4.0.1 depends on win32 >=4.0.0 <6.0.0, flick_video_player 0.7.0 is incompatible with package_info_plus >=4.0.1.
    So, because sidharta depends on both package_info_plus 5.0.1 and flick_video_player 0.7.0, version solving failed.`

**Comment by ttamas85** [comment]
same issue
