### ISSUE TITLE
_CastError: Null check operator used on a null value

### ISSUE THREAD

**Issue by GujjuFlutterGuy** [GeekyAnts/flick-video-player#227]
This is the error.

```
_CastError: Null check operator used on a null value
  File "video_manager.dart", line 144, in FlickVideoManager._changeVideo
```

Version:

> **flick_video_player: ^0.5.0**

Device: 

> **iPhone 11**

Suggestion:

Can we avoid bang operators? It would be perfect.

Code reference from **video_manager.dart**

![Screenshot 2023-05-31 at 10 49 55 AM](https://github.com/GeekyAnts/flick-video-player/assets/24433003/412fef6a-5d31-4372-898c-3fa9e49266b4)

**Comment by hortigado** [comment]
#https://github.com/GeekyAnts/flick-video-player/issues/90#issuecomment-845840535
I solved it with autoplay:false

**Comment by hortigado** [comment]
I realized that this problem is due to the fact that when we update some information of our widget, FlickVideoManager starts again. So with my state manager, in my case getx, I create a controller for the video and I check if it has already started, not to do it again

**Comment by geekruchika** [comment]
Closing this as it's need to be logically handle at codebase
