### ISSUE TITLE
On Exit Full Screen Video Player gets black.

### ISSUE THREAD

**Issue by mehroze-zaidi** [GeekyAnts/flick-video-player#228]
When I exit full-screen mode on flutter web the video player gets black but the audio keeps playing.
As you can see in the following screen video:

https://github.com/GeekyAnts/flick-video-player/assets/78612861/bbccab88-c026-4051-b621-06ce22fa2dc3

**Code:**

class CustomVideoPlayer extends StatefulWidget {
  const CustomVideoPlayer({super.key});

  @override
  State<CustomVideoPlayer> createState() => _CustomVideoPlayerState();
}

class _CustomVideoPlayerState extends State<CustomVideoPlayer> {
  late FlickManager flickManager;

  @override
  void initState() {
    flickManager = FlickManager(
    
      autoPlay: false,
      videoPlayerController: VideoPlayerController.network(
          "https://www.clevisto.com/out/clevisto/img/videos/films/nrg-5/nrg-5-riegel-notnahrung-kompaktweizenriegel-720p.mp4"),
    );

    super.initState();
  }

  @override
  void dispose() {
    flickManager.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 290,
      child: ClipRRect(
        borderRadius: const BorderRadius.all(Radius.circular(12)),
        child: FlickVideoPlayer(flickManager: flickManager),
      ),
    );
  }
}

**Flutter doctor summary:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by romilmavani** [comment]
Yes, I'm facing same issue we need to resolve this as soon as possible

**Comment by geekruchika** [comment]
May be this resolves it
https://github.com/GeekyAnts/flick-video-player/pull/248

**Comment by geekruchika** [comment]
Fixed in flick_video_player 0.7.0 version.
