### ISSUE TITLE
How to set seek control to top of player?

### ISSUE THREAD

**Issue by emcengineer** [GeekyAnts/flick-video-player#23]
Any quick ideas?

**Comment by ahujaraghav** [comment]
@emcengineer Code sample to play/pause video onTap of  Floating Action Button. Try something like this.

`import 'package:example/utils/mock_data.dart';
import 'package:flick_video_player/flick_video_player.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class DefaultPlayer extends StatefulWidget {
  DefaultPlayer({Key key}) : super(key: key);

  @override
  _DefaultPlayerState createState() => _DefaultPlayerState();
}

class _DefaultPlayerState extends State<DefaultPlayer> {
  FlickManager flickManager;
  @override
  void initState() {
    super.initState();
    flickManager = FlickManager(
      videoPlayerController:
          VideoPlayerController.network(mockData["items"][0]["trailer_url"]),
    );
    // Listen to changes in the video to re-render the controls.
    flickManager.flickVideoManager.addListener(_videoListener);
  }

  _videoListener() {
    // Re-render the widget to update the controls.
    setState(() {});
  }

  @override
  void dispose() {
    // Remove the listener.
    flickManager.flickVideoManager.removeListener(_videoListener);
    flickManager.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: FloatingButtonChild(
          isPlaying: flickManager.flickVideoManager.isPlaying,
        ),
        onPressed: () {
          flickManager.flickControlManager.togglePlay();
        },
      ),
      body: Column(
        children: <Widget>[
          Container(
            height: 300,
            child: FlickVideoPlayer(
              flickManager: flickManager,
              flickVideoWithControls: FlickVideoWithControls(
                controls: Container(),
              ),
              flickVideoWithControlsFullscreen: FlickVideoWithControls(
                controls: Container(),
              ),
            ),
          ),
          SizedBox(
            height: 100,
          ),
          Text(
            'Sample text widget',
            style: TextStyle(fontSize: 34),
          ),
        ],
      ),
    );
  }
}

class FloatingButtonChild extends StatelessWidget {
  const FloatingButtonChild({Key key, this.isPlaying}) : super(key: key);
  final bool isPlaying;

  @override
  Widget build(BuildContext context) {
    return isPlaying ? Icon(Icons.pause) : Icon(Icons.play_arrow);
  }
}`
