### ISSUE TITLE
Error When Run Project on iOS

### ISSUE THREAD

**Issue by andes2912** [GeekyAnts/flick-video-player#235]
Hello, i have issue when i run project on ios :
-  flick_video_player: ^0.3.1

Error: Member not found:
'SystemChrome.setEnabledSystemUIOverlays'.

**Comment by rohitprajapatii** [comment]
Can you provide more details? Or maybe try upgrading the package to the lastest version.

**Comment by geekruchika** [comment]
New updated version is up: 0.8.0. This should solve all the versions issue. Feel free to open this issue if needed.
