### ISSUE TITLE
Video play but audio not sound on IOS

### ISSUE THREAD

**Issue by thanhphong190** [GeekyAnts/flick-video-player#238]
Hi @ahujaraghav ahu @mrinaljain mr @geekruchika ge @rohitprajapatii hor
I dowload source and using link https://s3-north.viettelidc.com.vn/cjvina/1657245176_0.mp4 play video but not sound on IOS plaform, Please help check issue, thanks

**Comment by aloRanking** [comment]
I am facing this issue too. The video is playing but the audio is off. please help us to look into it.

**Comment by rohitprajapatii** [comment]
Hi @thanhphong190, the video you provided doesn't have the audio. The video seems to work fine in iOS.

**Comment by rohitprajapatii** [comment]
Well, we have also released a latest [version](https://pub.dev/packages/flick_video_player/versions/0.6.0), you can try that.

**Comment by thanhphong190** [comment]
> Well, we have also released a latest [version](https://pub.dev/packages/flick_video_player/versions/0.6.0), you can try that.

thanks @rohitprajapatii r
