### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by aloRanking** [GeekyAnts/flick-video-player#243]
Played Video does not have an audio. 
```[tasklist]
### Tasks
```

**Comment by aloRanking** [comment]
Please help look into it

**Comment by rohitprajapatii** [comment]
Can you please provide the video file you're using?

**Comment by rohitprajapatii** [comment]
Anyways, we've released a latest version, you can try that.

**Comment by aloRanking** [comment]
thank you!
