### ISSUE TITLE
Mismatch of minimum version of sdk and flutter in the pubspec.yaml file.

### ISSUE THREAD

**Issue by shanaka-sync** [GeekyAnts/flick-video-player#251]
version: 0.6.0

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.16.2"  # here

**Comment by Dheeraj7487** [comment]
Yes flutter version is above 3.13 and here is the plugin dart sdk is supported the 2.14. Mismatch the sdk version.

**Comment by geekruchika** [comment]
New updated version is up: 0.8.0. This should solve all the versions issue. Feel free to open this issue if needed.
