### ISSUE TITLE
Problem closing video in full screen (Navigator.pop)

### ISSUE THREAD

**Issue by thapp-com-br** [GeekyAnts/flick-video-player#26]
First of all congratulations on the beautiful work, it is perfectly suited to my project.

The package has a problem when displaying the video in full screen, when clicking close (Navigator.pop (context);) a black screen appears and the page does not return and the application stops working.

The problem is in this line (remembering that the error occurs only in full screen): https://github.com/GeekyAnts/flick-video-player/blob/master/example/lib/landscape_player/landscape_player_controls.dart#L138

A provisional alternative, would it be possible to hide Icons.cancel (from line 130 to 145) only in full screen?

It happens on a physical device, api 28 and 29 and others.

I hope you can reproduce the error, I look forward to the correction.

Ps. Sorry for the English, it's not my native language.

**Comment by ahujaraghav** [comment]
@thapp-com-br are you facing the issue with official example app also?
Alternatively try replacing Navigator.pop(context) with  flickManager.flickControlManager.exitFullscreen()

**Comment by thapp-com-br** [comment]
Yes, release also occurs.

His suggestion didn't work, he doesn't go back to the previous route, he just removes the full screen and puts it in portrait mode.

I ended up hiding the icon when he is using it in full screen (Orientation.portrait).

See what happens in the images.
![test](https://user-images.githubusercontent.com/65565758/91296385-e86d8100-e772-11ea-8087-f39284e1d2c0.png)

![Screenshot_1598439386](https://user-images.githubusercontent.com/65565758/91295967-3cc43100-e772-11ea-8314-7fbaec174819.png)
![Screenshot_1598439173](https://user-images.githubusercontent.com/65565758/91295961-3b930400-e772-11ea-9caa-0998431e4585.png)
![Screenshot_1598439189](https://user-images.githubusercontent.com/65565758/91295965-3cc43100-e772-11ea-9989-92a580a276e6.png)

**Comment by ahujaraghav** [comment]
@thapp-com-br can you please elaborate about what you are trying to achieve?

**Comment by thapp-com-br** [comment]
Where do I want to go, that the example you did:
https://github.com/GeekyAnts/flick-video-player/blob/master/example/lib/landscape_player/landscape_player_controls.dart#L130

Icone.close does not work if in that line:
https://github.com/GeekyAnts/flick-video-player/blob/master/example/lib/landscape_player/landscape_player.dart#L38

You replace that line:
         preferredDeviceOrientation: [
           DeviceOrientation.landscapeRight,
           DeviceOrientation.landscapeLeft
         ],

Per:
         preferredDeviceOrientation: [
           DeviceOrientation.portraitUp, // <== ADD
           DeviceOrientation.landscapeRight,
           DeviceOrientation.landscapeLeft
         ],

Test this way you will understand, thanks!

**Comment by AkbarBakhshi** [comment]
Hi. I am having the same problem. To reproduce it, you need to add `
                      FlickFullScreenToggle(
                        size: 20,
                      )` after `FlickSoundToggle(
                        size: 20,
                      ),` (line 122) in https://github.com/GeekyAnts/flick-video-player/blob/master/example/lib/landscape_player/landscape_player_controls.dart.

If you tap the x button on **full screen**, the app gets stuck.

**Comment by sahilgeekyants** [comment]
@thapp-com-br 
In order to use the cancel button in portraitUp orientation :
Either you can wrap the video player with the SafeArea()
```
 Scaffold(
   body: SafeArea(
    child: FlickVideoPlayer(
…
```
<img width="361" alt="safeArea_portraitUp_cancel" src="https://user-images.githubusercontent.com/60209052/118139074-a2516e00-b424-11eb-8f24-1d7f2d7c9b22.png">

Or you can disable the top padding which is blocking the cancel button to click in notch area by : 
Wrapping the Scaffold in MediaQuery.removePadding : 
```
MediaQuery.removePadding(
    context: context,
    removeTop: true,
    child: Scaffold(
    	body: FlickVideoPlayer(
...
```
![portraitUp_cancel](https://user-images.githubusercontent.com/60209052/118139163-b85f2e80-b424-11eb-885e-a0b1a7f4f336.png)

Please let us know if you face any other issues

**Comment by sahilgeekyants** [comment]
@AkbarBakhshi 
If you want to add FlickFullScreenToggle() button and enter the full screen mode then you can-not use the same code inside cancel button onTap() function to exit the screen.
Earlier it was
```
onTap: () {
              SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
              SystemChrome.setPreferredOrientations(
                  [DeviceOrientation.portraitUp]);
              Navigator.pop(context);
            },
```
But if you add full screen toggle then you can use
```
 onTap: () {
              if (controlManager.isFullscreen) {
                controlManager.exitFullscreen();
              }
              SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
              SystemChrome.setPreferredOrientations(
                  [DeviceOrientation.portraitUp]);
              Navigator.pop(context);
            },
```
where you can get **controlManager** by adding this in build function :
`  FlickControlManager controlManager = Provider.of<FlickControlManager>(context);`

Here is the preview:
![cancel_full_mode](https://user-images.githubusercontent.com/60209052/118143023-89e35280-b428-11eb-80ca-8976412fe383.gif)

Please let us know if you face any other issues

**Comment by dongyankun** [comment]
Navigator.popUntil(context, ModalRoute.withName('name'));

**Comment by geekruchika** [comment]
Feel free to open if issue still exists.

**Comment by fandofastest** [comment]
> @thapp-com-br are you facing the issue with official example app also? Alternatively try replacing `Navigator.pop(context)` with `flickManager.flickControlManager.exitFullscreen()`

super, work, for me
