### ISSUE TITLE
SeekTo Issue

### ISSUE THREAD

**Issue by KISHORE-KUMAR-S** [GeekyAnts/flick-video-player#260]
After seeking to a particular duration, the video stucks in the same place.

```
@override
  void initState() {
    super.initState();
    flickManager = FlickManager(
      videoPlayerController: VideoPlayerController.network(
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4?raw=true"),
    );
    flickManager.flickVideoManager!.addListener(_videoPlayingListener);
    flickManager.flickVideoManager!.videoPlayerController!.play();
  }

  _videoPlayingListener() async {
    flickManager.flickVideoManager!.videoPlayerController!
        .seekTo(Duration(seconds: 100));
    flickManager.flickVideoManager!.videoPlayerController!.pause();
  }

```

**Comment by itsAkshatG13** [comment]
Upon trying the mentioned video link could not encounter any seeking issues. In addition to checking the implementation, you can also check for internet connectivity in background as network videos playback depend on the internet connectivity. Here is a video of playback for your reference. The video file and the code seems to work fine.

https://github.com/user-attachments/assets/ef5c7d19-8f5c-46f3-828f-f8b3e49ece40
