### ISSUE TITLE
Package isn't working with Shared_Plus Package

### ISSUE THREAD

**Issue by TheUnknownCorp** [GeekyAnts/flick-video-player#266]
### Flick_Video_Player isn't working with Shared_Plus Package

I am coding an application that needs both `Shared_Plus` and `Flick_Video_Player`packages.  But both packages are causing version-solving errors.

**Log, when pub getting**
```
Because flick_video_player >=0.6.0 depends on wakelock ^0.6.2 which depends on wakelock_windows ^0.2.0, flick_video_player >=0.6.0 requires wakelock_windows ^0.2.0.
Because wakelock_windows >=0.2.1 depends on win32 ^3.0.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, every version of wakelock_windows requires win32 ^2.0.0 or ^3.0.0.
Thus, flick_video_player >=0.6.0 requires win32 ^2.0.0 or ^3.0.0.
And because share_plus 7.2.2 depends on win32 >=4.0.0 <6.0.0 and no versions of share_plus match >7.2.2 <8.0.0, flick_video_player >=0.6.0 is incompatible with share_plus ^7.2.2.
So, because _____Project Title_____depends on both share_plus ^7.2.2 and flick_video_player ^0.7.0, version solving failed.

**Comment by Lazizbek97** [comment]
any new ? have you fixed? @TheUnknownCorp

**Comment by Hilbert2048** [comment]
We should upgrade to wakelock_plus
https://github.com/fluttercommunity/wakelock_plus/tree/main/wakelock_plus

**Comment by devanupam** [comment]
> We should upgrade to wakelock_plus https://github.com/fluttercommunity/wakelock_plus/tree/main/wakelock_plus

Eagerly waiting for this upgrade.

**Comment by geekruchika** [comment]
New updated version is up: 0.8.0. This should solve all the versions issue. Feel free to open this issue if needed.
