### ISSUE TITLE
Package is not adding to pubspec 

### ISSUE THREAD

**Issue by shafi21064** [GeekyAnts/flick-video-player#268]
![image](https://github.com/GeekyAnts/flick-video-player/assets/96995242/985d547a-75e0-40fc-8a1a-0e91f4fec526)

**Comment by xiazhichao** [comment]
me too，Is there a solution?

**Comment by geekruchika** [comment]
New updated version is up: 0.8.0. This should solve all the versions issue. Feel free to open this issue if needed.
