### ISSUE TITLE
Can't Play AWS CloudFront m3u8 format on IOS only

### ISSUE THREAD

**Issue by SmarttersStudio** [GeekyAnts/flick-video-player#27]
By playing AWS cloud front video of m3u8 format it is working properly in android but in ios it is showing error without any message

**Comment by Gursewak-Uppal** [comment]
@SmarttersStudio can you please post your code here because I'm working on same and video format m3u8 is working on both side (Android & iOS)

**Comment by Mohamed-Elsayed-Nadsoft** [comment]
the same issue  
@SmarttersStudio  can fix this

**Comment by RounakTadvi** [comment]
I'm facing the same issue in iOS, the player does not displays any error while running the AWS Cloudfront m3u8 format manifest file.

**Comment by geekruchika** [comment]
@SmarttersStudio @RounakTadvi 
Can you please provide me a sample cloud front video of m3u8 format? It'll be easy for me to debug.
Thanks.

**Comment by geekruchika** [comment]
Please track here.
https://github.com/GeekyAnts/flick-video-player/issues/82
