### ISSUE TITLE
null value

### ISSUE THREAD

**Issue by Pawankant87** [GeekyAnts/flick-video-player#276]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      FlickVideoManager._changeVideo (package:flick_video_player/src/manager/video_manager.dart:144:57)
<asynchronous suspension>

**Comment by rohitprajapati0606** [comment]
@Pawankant87 Try, registering the context in your `FlickManager` using the `registerContext` method when initializing. This error occurs when you're not registering the context and then use the handleChangeVideo method. Feel free to let us know if you get any issues.

**Comment by rohitprajapatii** [comment]
@Pawankant87 Try, registering the context in your `FlickManager` using the `registerContext` method when initializing. This error occurs when you're not registering the context and then use the handleChangeVideo method. Feel free to let us know if you get any issues.

**Comment by yhelwa** [comment]
@rohitprajapatii I tried that but still getting same null check operator error.

`  void initFlickManager() {
    flickManager = FlickManager(
        videoPlayerController: _videoPlayerController,
        onVideoEnd: () async {
          if (!widget.video.done) {
            widget.video.done = true;
            await widget.addVideoRewardsAndActivity();
          }
        });
    flickManager.registerContext(context);
  }`

**Comment by yairsts** [comment]
this line couse the error.

`if (autoPlay && ModalRoute.of(_flickManager._context!)!.isCurrent)`

**Comment by geekruchika** [comment]
Added a fix in this PR: https://github.com/GeekyAnts/flick-video-player/pull/284/files.

**Comment by harpreetslabs** [comment]
> Added a fix in this PR: https://github.com/GeekyAnts/flick-video-player/pull/284/files.

Yes it fixed but we have to update package code, do you have another solution for now?

**Comment by geekruchika** [comment]
I'll merge release this soon.

**Comment by geekruchika** [comment]
Released 0.9.0.
