### ISSUE TITLE
Video not displaying fully in fullscreen mode.

### ISSUE THREAD

**Issue by cbahai** [GeekyAnts/flick-video-player#278]
Video not displaying fully in fullscreen mode  .

The video address is "https://streaminghkjc-a.akamaihd.net/hdflash/twstarter/2024/20240519/01/novo/twstarter_20240519_01_novo_1200kbps.mp4" .

![image](https://github.com/GeekyAnts/flick-video-player/assets/5957012/fea47e69-4e53-436b-81d1-d1aa034cb1c0)  

![image](https://github.com/GeekyAnts/flick-video-player/assets/5957012/c829f2cf-b15d-4e9f-9697-692a1a080c03)

**Comment by perzend** [comment]
Hi! In my case, in the FlickVideoWithControls widget, I just set the videoFit value to BoxFit.contain. By default, it's BoxFit.cover.
```
FlickVideoPlayer(
        flickManager: flickManager,
        flickVideoWithControls: FlickVideoWithControls(
          videoFit: BoxFit.contain,
          ....
        ),
       ....
)
```

**Comment by cbahai** [comment]
> Hi! In my case, in the FlickVideoWithControls widget, I just set the videoFit value to BoxFit.contain. By default, it's BoxFit.cover.
> 
> ```
> FlickVideoPlayer(
>         flickManager: flickManager,
>         flickVideoWithControls: FlickVideoWithControls(
>           videoFit: BoxFit.contain,
>           ....
>         ),
>        ....
> )
> ```

it is ok, thanks.
