### ISSUE TITLE
Supporting Youtube Videos 

### ISSUE THREAD

**Issue by tanveer1302** [GeekyAnts/flick-video-player#28]
Does it support playing youtube videos? If not, then are there any plans for that. 

Reference: https://pub.dev/packages/ext_video_player

ext_video_player plugin is basic one without much controls.

**Comment by ahujaraghav** [comment]
@tanveer1302 currently youtube videos are not supported due to some technical blockers.

**Comment by geekruchika** [comment]
You can use Youtube explode to get playback URLs and use it in Flick player
https://pub.dev/packages/youtube_explode_dart

**Comment by Bartozo** [comment]
@geekruchika  I have experienced this problem, but your solution didn't help. Could you provide more information on how to solve this issue? (here is a link to my issue just in case https://github.com/GeekyAnts/flick-video-player/issues/97)
