### ISSUE TITLE
cant play .mov in ios

### ISSUE THREAD

**Issue by pokid** [GeekyAnts/flick-video-player#289]
in ios,local video mine is .mov,it cant play .mov video

**Comment by itsAkshatG13** [comment]
.mov videos are supported and seem to work fine. Please check the video file incase it has issues playing. Here is a demonstration of the .mov file that we tried playing. Also attaching the playback for your reference. Try out with this .mov file and Incase of anything specific please provide the codebase and exact scenario to understand better.

Video url: [.mov file](https://res.cloudinary.com/dchqzsuh8/video/upload/v1724307442/flickplayer/videos/j78pgb53xgovdobkorof.mov) 

Uploading Screen Recording.mov…
