### ISSUE TITLE
Resume Video From Last Position

### ISSUE THREAD

**Issue by RNSuthar** [GeekyAnts/flick-video-player#29]
How can I listener the completion & seek-bar time.

**Comment by ahujaraghav** [comment]
https://github.com/GeekyAnts/flick-video-player/issues/20

**Comment by ahujaraghav** [comment]
You can listen to changes on flickVideoManager.
```  flickManager.flickVideoManager.addListener(_videoPlayingListener);```

**Comment by RNSuthar** [comment]
Thank you so much
