### ISSUE TITLE
How to add Safe Area for buttons in full screen?

### ISSUE THREAD

**Issue by ZsIsMe** [GeekyAnts/flick-video-player#295]
Thank you very much for your great work!

I'm encountering an issue where, when playing in fullscreen mode, the bottom buttons are extending beyond the safe area. How should I resolve this issue?
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/0f64adba-469d-4a3a-b7e0-1986c24e0309">

**Comment by ge0rge000** [comment]
i have solution play from youtybe and solution also for get all quality for youtube contact me on whatsapp :971557474526
