### ISSUE TITLE
How to Make Playing Video selected or highlighted from play list ?

### ISSUE THREAD

**Issue by Rammehar** [GeekyAnts/flick-video-player#3]
I tried CustomOrientationPlayer  flick-video-player  every thing worked fine but don't find how to make playing video highlighted. any suggestion would be appreciated. Thank You

**Comment by ahujaraghav** [comment]
@Rammehar Can you please explain what you mean by playing video highlight?

**Comment by Rammehar** [comment]
Playing video highlight means.the video which is playing , how to heightlight the name of that video.  
![pic](https://user-images.githubusercontent.com/8978743/85016434-5734c980-b187-11ea-8c29-20b1abe31d22.jpeg)

**Comment by ahujaraghav** [comment]
@Rammehar you can make DataManager class extend ChangeNotifier and listen to changes in the UI. Your UI will then auto-update whenever you call notifyListeners inside DataManager.
