### ISSUE TITLE
Support for web

### ISSUE THREAD

**Issue by jamesmoore255** [GeekyAnts/flick-video-player#33]
Hey,

First I just want to say thanks for the package, it's really great and easy to use.

Is support for web in the pipeline?

Thanks!

**Comment by ahujaraghav** [comment]
@jamesmoore255 yes, we are planning for the same.

**Comment by krisztianodor** [comment]
Any update on this?

**Comment by geekruchika** [comment]
Yes!

Flick player has web support. Though we have to add all keyboard controls as flutter renders on canvas and will not get the default keyboard browser controls.

Please try this out and let me know if you get any issues.
Enhancement PRs always appreciated.

Closing this issue. Please create a new issue if you have rendering issues. Thanks.
