### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by dmoss733** [GeekyAnts/flick-video-player#39]
It would be excellent to see playback speed added to this. The ability to slow down or speed up video would be very helpful.

**Comment by dmoss733** [comment]
Note this was added in the video player in v.11 so as long as you update that dependency you can add this functionality.

**Comment by geekruchika** [comment]
Thanks for pointing.
This will soon be reflected in the plugin. Implementation has already done.
Track in this PR (https://github.com/GeekyAnts/flick-video-player/pull/79)
Closing this issue.
