### ISSUE TITLE
videoFit not working

### ISSUE THREAD

**Issue by vishwajit76** [GeekyAnts/flick-video-player#4]
FlickVideoWithControls videoFit not working and preview is zoomed.

![WhatsApp Image 2020-06-19 at 5 05 48 PM](https://user-images.githubusercontent.com/25575802/85128586-39329c00-b24f-11ea-871c-fae073738213.jpeg)

**Comment by ahujaraghav** [comment]
@vishwajit76 Please check this [example](https://github.com/GeekyAnts/flick-video-player/blob/example/custom-fit-player/example/lib/custom_fit_player/custom_fit_player.dart).
