### ISSUE TITLE
Ability to set text style for the FlickLeftDuration

### ISSUE THREAD

**Issue by Filiponesco** [GeekyAnts/flick-video-player#41]
Nowadays widget FlickLeftDuration has the following parameters: fontSize and color. So i can't change: font family, fontWeight e.t.c. The ability to set text style would be good.

**Comment by ahujaraghav** [comment]
@Filiponesco did you try using [```DefaultTextStyle```](https://api.flutter.dev/flutter/widgets/DefaultTextStyle-class.html)?

**Comment by Filiponesco** [comment]
Thanks it works.
