### ISSUE TITLE
multi player problem

### ISSUE THREAD

**Issue by gulmensedat** [GeekyAnts/flick-video-player#42]
I used 5 subordinate default players
1 player takes up approximately 3/1 of the screen.
I click on the first player, I watch the video, the top video when I land the lowest video starts to load again and the time I stop is deleted automatically. I want it protected. How do I get it?

**Comment by geekruchika** [comment]
Sorry didn't get your issue. Can you please provide some demo or code snippets where you are facing this issue?

**Comment by geekruchika** [comment]
Feel free to reopen if required.
