### ISSUE TITLE
Is there a way to set buffer object values

### ISSUE THREAD

**Issue by mrinaljain** [GeekyAnts/flick-video-player#48]
Is there a way to set buffer object values so that video streaming can be improved?

MIN_BUFFER_DURATION
MAX_BUFFER_DURATION
MIN_PLAYBACK_START_BUFFER
MIN_PLAYBACK_RESUME_BUFFER

**Comment by mrinaljain** [comment]
We have found a solution to this .
Thanks

**Comment by geekruchika** [comment]
Closing it.
