### ISSUE TITLE
Full screen portrait video

### ISSUE THREAD

**Issue by leszekkrol** [GeekyAnts/flick-video-player#51]
Hi, When I play video in portrait mode, e.g. 1080x1920, I click watch in full screen. The application screen rotates to the landscape screen. However, the video is projected to the full width of the phone and not to the video height, so I can only see part of my video.

**Comment by ahujaraghav** [comment]
@leszekkrol try changing the ```videoFit``` on ```FlickVideoWithControls```

**Comment by leszekkrol** [comment]
@ahujaraghav Actually the tip works fine, thank you very much 👍
