### ISSUE TITLE
HLS Stream (m3u8 Video) support

### ISSUE THREAD

**Issue by gdg4dev** [GeekyAnts/flick-video-player#52]
It would be nice to have hls/m2u8 support

**Comment by Hi99simon** [comment]
I guess it is possible.
I used m2u8 url and possible to stream

**Comment by Mohamed-Elsayed-Nadsoft** [comment]
@Hi99simon  can shared code

**Comment by geekruchika** [comment]
I tried some m2m8 URLs from https://ottverse.com/free-hls-m3u8-test-urls/. It's working in Player v0.2.0. Let me know if there are any specific URLs not working. 
Thank you. Feel free to open this issue if this still persists.

**Comment by NehaKushwah993** [comment]
This Url is not working : https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8

**Comment by ansh-les** [comment]
DId you manage to get subtitles working with .m3u8 in flick video player?
