### ISSUE TITLE
attaching thumbnails

### ISSUE THREAD

**Issue by leszekkrol** [GeekyAnts/flick-video-player#53]
Hi, is it possible to attach any thumbnail to a video file? My application stores these thumbnails on the server, but I have a black screen when buffering a larger video file. I would like to put a thumbnail there 🥇

**Comment by ahujaraghav** [comment]
You can use ```playerLoadingFallback``` on ```FlickVideoWithControls```. Checkout examples, we have loading fallback implementations.
