### ISSUE TITLE
Android back btn

### ISSUE THREAD

**Issue by leszekkrol** [GeekyAnts/flick-video-player#54]
Is it possible to exit video in landscape mode with the android back button?

**Comment by ahujaraghav** [comment]
This feature is enabled by default, can you share code snippets, and some Screenshots for the issue.

**Comment by leszekkrol** [comment]
@ahujaraghav it's weird. We implement video player in accordance with the basic guidelines from the technical documentation. Example bottom:

`import 'package:flutter/material.dart';
import 'package:flick_video_player/flick_video_player.dart';
import 'package:video_player/video_player.dart';

class SamplePlayer extends StatefulWidget {
  SamplePlayer({Key key}) : super(key: key);

  @override
  _SamplePlayerState createState() => _SamplePlayerState();
}

class _SamplePlayerState extends State<SamplePlayer> {
  FlickManager flickManager;
  @override
  void initState() {
    super.initState();
    flickManager = FlickManager(
      videoPlayerController:
          VideoPlayerController.network("url"),
    );
  }

  @override
  void dispose() {
    flickManager.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: FlickVideoPlayer(
        flickManager: flickManager
      ),
    );
  }
}`

There is also a WillPopScope component in the class in which we embed the video.

**Comment by ahujaraghav** [comment]
Can you try removing the WillPopScope from the class in which you embed the video.

**Comment by leszekkrol** [comment]
@ahujaraghav  unfortunately for this screen it is necessary to use this component. Is there any other way to intercept this event? however, I confirm removing this component solves the issue

**Comment by ahujaraghav** [comment]
@leszekkrol ok in that case try adding this code in ```onWillPop``` 
```  if (flickManager.flickControlManager.isFullscreen) {
            flickManager.flickControlManager.exitFullscreen();
          }```

**Comment by leszekkrol** [comment]
It will definitely be a challenge, because the screen contains a lot of smaller widgets. Nevertheless, thank you for your help :)
