### ISSUE TITLE
How can I get the time when video pause?

### ISSUE THREAD

**Issue by Zuozihao** [GeekyAnts/flick-video-player#55]

**Comment by ahujaraghav** [comment]
Same as #13

**Comment by Zuozihao** [comment]
> Same as #13

If I drag the progress,how can I get the correct time?Help me ,thx.

**Comment by Zuozihao** [comment]
> > Same as #13
> 
> If I drag the progress,how can I get the correct time?Help me ,thx.

fixed with 
`Duration duration =
            _flickManager.flickVideoManager.videoPlayerValue.position;`
