### ISSUE TITLE
The subtitles are blocked in full screen.

### ISSUE THREAD

**Issue by msterzhang** [GeekyAnts/flick-video-player#56]
![image](https://user-images.githubusercontent.com/31364579/98624486-e31edc00-2348-11eb-8526-f83f9c382522.png)
![image](https://user-images.githubusercontent.com/31364579/98624497-e9ad5380-2348-11eb-98e9-bfe6741cafb9.png)

**Comment by ahujaraghav** [comment]
@msterzhang can you please describe the issue

**Comment by msterzhang** [comment]
> @msterzhang can you please describe the issue

Thank you for your reply，The mobile phone screen ratio adapted by the application is 16:9, and the full-screen mobile phone screen ratio is greater than or equal to 18:9. After the video is full, it will be stretched, causing the subtitles to be blocked.

**Comment by ahujaraghav** [comment]
@msterzhang did you try changing the ```videoFit``` property in fullscreen mode like this

``` 
FlickVideoPlayer(
          flickManager: flickManager,
          flickVideoWithControls: FlickVideoWithControls(
            controls: FlickPortraitControls(),
          ),
          flickVideoWithControlsFullscreen: FlickVideoWithControls(
            controls: FlickLandscapeControls(),
            videoFit: BoxFit.contain,
          ),
        )
```

**Comment by msterzhang** [comment]
I haven't tried it like this. I will test it when I come home from a business trip, thank you!

**Comment by msterzhang** [comment]
> @msterzhang did you try changing the `videoFit` property in fullscreen mode like this
> 
> ```
> FlickVideoPlayer(
>           flickManager: flickManager,
>           flickVideoWithControls: FlickVideoWithControls(
>             controls: FlickPortraitControls(),
>           ),
>           flickVideoWithControlsFullscreen: FlickVideoWithControls(
>             controls: FlickLandscapeControls(),
>             videoFit: BoxFit.contain,
>           ),
>         )
> ```

Thank you very much for your work, this is effective!

**Comment by vipinnegi90** [comment]
@msterzhang How did you manage to get subtitles? Is it embedded on video or different file?

**Comment by msterzhang** [comment]
> @msterzhang How did you manage to get subtitles? Is it embedded on video or different file?

embedded on video

**Comment by vipinnegi90** [comment]
Okay thanks
