### ISSUE TITLE
Fullscreen crash

### ISSUE THREAD

**Issue by leszekkrol** [GeekyAnts/flick-video-player#57]
Hello, After running a video on fullscreen we get this crash

`I/flutter (24541): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (24541): The following assertion was thrown building Container(constraints: BoxConstraints(w=320.0,
I/flutter (24541): h=320.0)):
I/flutter (24541): A VideoPlayerController was used after being disposed.
I/flutter (24541): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
I/flutter (24541): 
I/flutter (24541): The relevant error-causing widget was:
I/flutter (24541):   Container
I/flutter (24541):   file:///Users/uogforceone/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flick_video_player-0.1.1/lib/src/widgets/flick_native_video_player.dart:38:19
I/flutter (24541): 
I/flutter (24541): When the exception was thrown, this was the stack:
I/flutter (24541): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
I/flutter (24541): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
I/flutter (24541): #2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:195:12)
I/flutter (24541): #3      _VideoPlayerState.didUpdateWidget (package:video_player/video_player.dart:547:26)
I/flutter (24541): #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4862:57)
I/flutter (24541): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:3367:15)
I/flutter (24541): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6171:14)
I/flutter (24541): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3367:15)
I/flutter (24541): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4700:16)
I/flutter (24541): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
I/flutter (24541): #10     StatelessElement.update (package:flutter/src/widgets/framework.dart:4756:5)
I/flutter (24541): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3367:15)
I/flutter (24541): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6171:14)
I/flutter (24541): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3367:15)
I/flutter (24541): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6171:14)
I/flutter (24541): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3367:15)
I/flutter (24541): #16     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:136:18)
I/flutter (24541): #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
I/flutter (24541): #18     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)
I/flutter (24541): #19     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
I/flutter (24541): #20     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter (24541): #21     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
I/flutter (24541): #22     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
I/flutter (24541): #23     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:351:5)
I/flutter (24541): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #25     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:395:14)
I/flutter (24541): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #27     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:565:15)
I/flutter (24541): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #31     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:353:14)
I/flutter (24541): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #33     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
I/flutter (24541): #34     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:911:7)
I/flutter (24541): #35     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
I/flutter (24541): #36     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
I/flutter (24541): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #41     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1306:11)
I/flutter (24541): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #43     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
I/flutter (24541): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (24541): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (24541): #55     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
I/flutter (24541): #56     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (24541): #57     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (24541): #58     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:454:19)
I/flutter (24541): #59     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:895:13)
I/flutter (24541): #60     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
I/flutter (24541): #61     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (24541): #62     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (24541): #63     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (24541): #67     _invoke (dart:ui/hooks.dart:157:10)
I/flutter (24541): #68     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:256:5)
I/flutter (24541): #69     _drawFrame (dart:ui/hooks.dart:120:31)
I/flutter (24541): (elided 3 frames from dart:async)
I/flutter (24541): 
`

**Comment by ahujaraghav** [comment]
@leszekkrol Can you share code snippets for the same.

**Comment by leszekkrol** [comment]
The problem only occurs on Android 10

**Comment by geekruchika** [comment]
Hey @leszekkrol 
Can't able to reproduce this issue on Android 10. Please try v0.2.0 and feel free to open this issue if you face the same. Thank you. Happy Coding!!
