### ISSUE TITLE
How do I Unload A Video

### ISSUE THREAD

**Issue by RalphMarvin** [GeekyAnts/flick-video-player#59]
I have a list of videos loaded from the server. Am using this plugin to display and play the video. My problem is when remove the video from the list, it still remains on the screen i want to know a way of unloading the video. I tried calling dispose but it didn't work.

**Comment by geekruchika** [comment]
Can you please provide more detail with code snippet & video if possible?

**Comment by geekruchika** [comment]
Closing it for further info. Please feel free to open it if still needed.
