### ISSUE TITLE
Fullscreen video doesn't rotate to landscape on iOS

### ISSUE THREAD

**Issue by gtroncone** [GeekyAnts/flick-video-player#62]
When I click the video to go fullscreen it expands into portrait up, this only happens on iOS (both a real device, via TestFlight, and a simulator), yet it works correctly on android.

These are the contents of my build function for that particular screen.

    return SingleChildScrollView(
      child: Padding(
        padding: widget.customBorder ?? EdgeInsets.zero,
        child: ClipRRect(
          borderRadius: BorderRadius.circular(13),
          child: FlickVideoPlayer(
            flickManager: flickManager,
            preferredDeviceOrientationFullscreen: const [
              DeviceOrientation.landscapeLeft,
              DeviceOrientation.landscapeRight,
            ],
            flickVideoWithControls: FlickVideoWithControls(
              controls: CustomVideoPlayerControls(),
            ),
            flickVideoWithControlsFullscreen: FlickVideoWithControls(
              controls: CustomVideoPlayerControls(
                fullscreen: true,
              ),
            ),
          ),
        ),
      ),
    );

Do you have any idea of what could be happening? Any assistance would be greatly appreciated.

Please let me know if you require any additional information.

![simulator_screenshot_E1D8809E-D481-431C-A7AC-2E2BFCBCC33E](https://user-images.githubusercontent.com/43040157/102262630-48975700-3f0b-11eb-80b4-b6dab23e0952.png)

**Comment by ankitsaurabhinfosys** [comment]
how did you solve this?
