### ISSUE TITLE
flick_video_player 0.1.1 depends on video_player ^0.10.8+1 and no versions of flick_video_player match >0.1.1 <0.2.0, flick_video_player ^0.1.1 requires video_player ^0.10.8+1.

### ISSUE THREAD

**Issue by izark99** [GeekyAnts/flick-video-player#63]
Because flick_video_player 0.1.1 depends on video_player ^0.10.8+1 and no versions of flick_video_player match >0.1.1 <0.2.0, flick_video_player ^0.1.1 requires video_player ^0.10.8+1.
So, because KhoPhim depends on both video_player ^0.11.1+5 and flick_video_player ^0.1.1, version solving failed.

Please update package with new video_player version.

**Comment by Happ2y** [comment]
nayamat_app depends on both flick_video_player ^0.3.1 and provider ^6.0.2, version solving failed
