### ISSUE TITLE
In iOS local downlaoded m3u8 video file is not playing

### ISSUE THREAD

**Issue by Jai05-techie** [GeekyAnts/flick-video-player#67]
Hi,

i have tried to play downloaded m3u8 video file in iOS. Its not playing and error also not showing.

Eg:

```
File fp = File('LocalVideoPath');
flickManager = FlickManager(
      videoPlayerController: VideoPlayerController.file(fp),
    );

```

**Comment by optimusvish** [comment]
@Jai05-techie Same issue I am also facing any work around you got ?

**Comment by geekruchika** [comment]
Please track here.
https://github.com/GeekyAnts/flick-video-player/issues/82
