### ISSUE TITLE
Regarding aspectratio

### ISSUE THREAD

**Issue by spyderbibek** [GeekyAnts/flick-video-player#7]
Is there anyway to change the aspect ratio of the video player?

**Comment by mrinaljain** [comment]
Just wrap the video player widget with an AspectRatio widget and use whatever aspect ratio you want to use.

`AspectRatio(
     aspectRatio: 16 / 9,
       child: Container(
           child: FlickVideoPlayer(),
     ),
   ),`

**Comment by spyderbibek** [comment]
doesn't work like that. video content is cropped and using aspect ratio doesn't fixes that. anyways coded my own solution so this can be closed.

**Comment by shiv2299** [comment]
> doesn't work like that. video content is cropped and using aspect ratio doesn't fixes that. anyways coded my own solution so this can be closed.

hi can you please tell how did you solve the issue

**Comment by tibfox** [comment]
for everyone who has the same issue: You can use the videoFit attribute in FlickVideoWithControls to contstraint the video into a defined height: 
```
 Container(
        height: widget.height,
        child: FlickVideoPlayer(
          flickManager: flickManager,
          flickVideoWithControls: FlickVideoWithControls(
            videoFit: BoxFit.fitHeight,
            controls: const FlickPortraitControls(),
          ),
        ));```
