### ISSUE TITLE
Multiple Videos Issue 

### ISSUE THREAD

**Issue by Tejareddy94** [GeekyAnts/flick-video-player#70]
I have developed an app  similar to instagram in Bottom Navigation bar i have News Feed and another is Porfile both contains videos in List view so i used Indexed Stack so the issue is when i open the app. The video in Porfile is getting played even thogh the tab is not open. I have used same Multi Manger for both the Tab i.e for news Feed and Profile. i have no idea what went wrong can any one help me on this issue ?

**Comment by code613** [comment]
@Tejareddy94 can you explain how you solved this issue?
