### ISSUE TITLE
All videos are playing in ListView

### ISSUE THREAD

**Issue by rizwika94** [GeekyAnts/flick-video-player#72]
I have a ListView, i have added 4 videos , all the videos are playing at the same time, also tapping on mute button, makes all the videos mute. How to play one video at the time, when switching over to other videos it should stop .

**Comment by ali9653** [comment]
Use VisibilityDetector

**Comment by geekruchika** [comment]
Please check out the Feedplayer example in the example app. It's there.

**Comment by sanchitmit26** [comment]
> Please check out the Feedplayer example in the example app. It's there.

Hello Mam
But Feedplayer is not working in Release mode. Please help
