### ISSUE TITLE
flick_video_player 0.1.1 depends on video_player ^0.10.8+1

### ISSUE THREAD

**Issue by vipinnegi90** [GeekyAnts/flick-video-player#73]
Can you please update the video_player version on your plugin? AFAIK, The new video player version contains tweaks related to HLS/m3u8 playing support for iOS. 

Ref: https://github.com/flutter/flutter/issues/48670#issuecomment-694866345

**Comment by abdulllrashid** [comment]
You can add this to your pubspec.yaml and get it compiled 

`flick_video_player:
    git:
      url: https://github.com/abdulllrashid/flick-video-player.git`

**Comment by geekruchika** [comment]
It's updated in version 0.2.0.
https://github.com/GeekyAnts/flick-video-player/tree/v0.2.0

Please feel free to open if there is any issue. Thank you.
