### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by MeAtPros** [GeekyAnts/flick-video-player#76]
flick_video_player from git which depends on provider ^4.0.5, provider ^4.0.5 is required.

**Comment by MeAtPros** [comment]
@gauravguha Any update?

**Comment by MeAtPros** [comment]
@ahujaraghav Any update?

**Comment by geekruchika** [comment]
It's updated in version 0.2.0.
https://github.com/GeekyAnts/flick-video-player/tree/v0.2.0

Please feel free to open if there is any issue. Thank you.
