### ISSUE TITLE
Bigger buttons/controls on deafult player

### ISSUE THREAD

**Issue by soyaaron** [GeekyAnts/flick-video-player#8]
Hi, sorry if this is not the right place to ask, but i'd like to know if there's a simple way of making these controls bigger, thanks! 
![image](https://user-images.githubusercontent.com/44642390/87343606-22fcc080-c51b-11ea-8321-5d32e656e6e9.png)

**Comment by ahujaraghav** [comment]
Hi @soyaaron with Flick you can easily customise the player as per your need, in your case you can use `iconSize` property of `FlickPortraitControls` to change the control's size.
