### ISSUE TITLE
Can't seek auto on slide bar player

### ISSUE THREAD

**Issue by Kimsoer** [GeekyAnts/flick-video-player#80]
I have problem when I seek on slide bar player, it always replay

**Comment by geekruchika** [comment]
Hi @Kimsoer 
Can you please share a small video clip for reference?

**Comment by Kimsoer** [comment]
here is video link https://drive.google.com/file/d/187usBvMkCh58tjMi_iqxvO5ddouKH6Y6/view?usp=sharing

**Comment by geekruchika** [comment]
@Kimsoer 

Please send a code snippet of how are you using it?

**Comment by Kimsoer** [comment]
Step 1: Initialize :
 FlickManager flickManager;
  VideoPlayerController videoPlayerController;

 videoPlayerController = VideoPlayerController.network("$url");
    flickManager = FlickManager(
      videoPlayerController: videoPlayerController,
    );

Step 2: call usage: 

AspectRatio(
                        aspectRatio: 16 / 9,
                        child: FlickVideoPlayer(
                        flickManager: model.flickManager)
)

**Comment by geekruchika** [comment]
Are you doing any setstate() on onChange of Slide bar?
Please try to run the example app added in the plugin and let me know if you get the same issue. Thanks.
It may be implementation issue too.

**Comment by geekruchika** [comment]
@Kimsoer Let me know if you are able to resolve it. Closing this issue meanwhile. Please open if still you are stuck.
