### ISSUE TITLE
package update to support null-safety.

### ISSUE THREAD

**Issue by inc16sec** [GeekyAnts/flick-video-player#81]
I'm using this package in my project but the problem is that I have already migrated to `Flutter 2.0.3 ` and `Dart sdk: '>=2.12.0 <3.0.0'` while this package is still legacy (not supporting null-safety). Is there any chance we gonna get to see an update of the package that will support null-safety in the near future? Thank you.

**Comment by geekruchika** [comment]
Yes, We are on it. Soon we will release it.

**Comment by inc16sec** [comment]
> Yes, We are on it. Soon we will release it.

Glad to hear that. Thank you.

**Comment by geekruchika** [comment]
> > Yes, We are on it. Soon we will release it.
> 
> Glad to hear that. Thank you.

It's done. Please try out.

**Comment by inc16sec** [comment]
Looks good. Thank you so much for the package and for taking the time to maintain it.
