### ISSUE TITLE
iOS unable to play m3u8 file format

### ISSUE THREAD

**Issue by vipinnegi90** [GeekyAnts/flick-video-player#82]
In Android all files are being played without any issue, but iOS is not able to play m3u8 file format.
You can check the below link for debug:
https://4ykn7mxvnwqg-hls-push.5centscdn.com/mp4/raw/Just%20A%20Minute2/Just%20a%20min_2_FINAL_2_combined.smil/playlist.m3u8

Since m3u8 files are basically playlist for different quality format, It would be great addition in package to allow select video quality for m3u8 files.

**Comment by geekruchika** [comment]
> In Android all files are being played without any issue, but iOS is not able to play m3u8 file format.
> You can check the below link for debug:
> https://4ykn7mxvnwqg-hls-push.5centscdn.com/mp4/raw/Just%20A%20Minute2/Just%20a%20min_2_FINAL_2_combined.smil/playlist.m3u8
> 
> Since m3u8 files are basically playlist for different quality format, It would be great addition in package to allow select video quality for m3u8 files.

Can you please share the logs you get after running m3u8 file format in iOS?

**Comment by geekruchika** [comment]
> In Android all files are being played without any issue, but iOS is not able to play m3u8 file format.
> You can check the below link for debug:
> https://4ykn7mxvnwqg-hls-push.5centscdn.com/mp4/raw/Just%20A%20Minute2/Just%20a%20min_2_FINAL_2_combined.smil/playlist.m3u8
> 
> Since m3u8 files are basically playlist for different quality format, It would be great addition in package to allow select video quality for m3u8 files.

@vipinnegi90 
The player can able to play the m3u8 file format. I have tried several URLs (e.g: https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8).

I guess there is something specific issue to this attached URL. I'll look into it and let you know.

**Comment by vipinnegi90** [comment]
> Can you please share the logs you get after running m3u8 file format in iOS?

the error : 
```
flutter: CacheManager: Failed to download file from  with error:
Invalid argument(s): No host specified in URI
```

**Comment by geekruchika** [comment]
> > Can you please share the logs you get after running m3u8 file format in iOS?
> 
> the error :
> 
> ```
> flutter: CacheManager: Failed to download file from  with error:
> Invalid argument(s): No host specified in URI
> ```

Strange!
Can you please try https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8. and share logs.

**Comment by vipinnegi90** [comment]
> Strange!
> Can you please try https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8. and share logs.
URL you provided is playing in both Android and iOS flawlessly. Not sure why my URL is not being played only in iOS :(

**Comment by geekruchika** [comment]
Closing this issue as not reproducible.

**Comment by soham-sharpsell** [comment]
Same issues happening in ios 17. 
in ios 14 its working fine.
