### ISSUE TITLE
[Web] Canvaskit Rendering Does Not Open Fullscreen Properly

### ISSUE THREAD

**Issue by msoham123** [GeekyAnts/flick-video-player#84]
![image](https://user-images.githubusercontent.com/51520568/115654396-f06fc780-a2e5-11eb-9050-97299a3fd3d2.png)

When I hit the fullscreen button on the FlickVideoPlayer widget, it expands to fill the screen but does not go into fullscreen. If I manually hit F11, it goes into full screen and replicates the expected behavior?

Is there a widget setting I am missing or is this just genuinely not working as intended on CanvasKit?

**Comment by geekruchika** [comment]
Still, we have to make the player compatible with the web.
If you are working on it, PRs are always welcomed!!🙂

**Comment by msoham123** [comment]
@geekruchika I'll see what I can do but I'm not super familiar with WASM and low-level web rendering things so I don't think I could make a PR as of now. I'll keep this up so that if someone who knows how to approach this can take a look at it.

**Comment by mrinaljain** [comment]
Hello @msoham123  I'm facing the same issue , did you tried the html render ?

**Comment by msoham123** [comment]
@mrinaljain No, I haven't. I would like to use the canvaskit renderer if possible, as it is more performant when it comes to scrolling.

This issue might be fixed once https://github.com/flutter/flutter/issues/80524#issuecomment-823060588 goes into master. We'll see.

**Comment by ditman** [comment]
https://github.com/flutter/flutter/issues/80524 has been merged into Flutter channel `master`. I hope it helps with this issue!

**Comment by msoham123** [comment]
I just tested it with the new fix. The problem still persists. The issue is not that fullscreen is not working. The issue is that the implementation of fullscreen covers the entire browser view instead of going into "expected" fullscreen.

![image](https://user-images.githubusercontent.com/51520568/119215884-4ff7f900-ba85-11eb-8fcb-31f632b746ee.png)

For example, when you go into fullscreen, you shouldn't be able to see any of my tabs or bookmarks.

**Comment by geekruchika** [comment]
Please try this version. It's still in development but you can able to toggle fullscreen.
https://pub.dev/packages/flick_video_player/versions/0.4.0-dev.1

**Comment by msoham123** [comment]
@geekruchika Fullscreen is still not working on latest master and version 0.4.0-dev.1.

Flutter 2.4.0-5.0.pre.109 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0874e421f7 (44 minutes ago) • 2021-07-20 13:46:04 -0400
Engine • revision f0325b6a3d
Tools • Dart 2.14.0 (build 2.14.0-332.0.dev)

The player attempts to fullscreen but stops.
