### ISSUE TITLE
Start video on specific position

### ISSUE THREAD

**Issue by DineshTaral12** [GeekyAnts/flick-video-player#85]
i need to play video from specific position like udemy, how to achieve this ?

**Comment by anandyadav21219** [comment]
yes, I am also looking for this solution.

**Comment by rohitprajapatii** [comment]
This may help.
`Future<void> skipToAPosition(Duration duration) async {
    flickManager.flickVideoManager?.addListener(() async {
      if (flickManager
              .flickVideoManager?.videoPlayerValue?.position.inSeconds ==
          0) {
        await flickManager.flickControlManager?.seekTo(duration);
      }
    });
  }`

Pass the duration for any video you want to start at a specific position.
