### ISSUE TITLE
Exception is thrown when creating FlickManager

### ISSUE THREAD

**Issue by mkranus** [GeekyAnts/flick-video-player#90]
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      FlickVideoManager._changeVideo (package:flick_video_player/src/manager/video_manager.dart:144:57)
#1      FlickVideoManager._handleChangeVideo (package:flick_video_player/src/manager/video_manager.dart:104:7)
#2      new FlickManager (package:flick_video_player/src/manager/flick_manager.dart:34:25)
```

**Flutter Doctor**:
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
```

**Comment by geekruchika** [comment]
Please attach a code snippet of how are you implementing it?

Can't able to reproduce it.

**Comment by mrinaljain** [comment]
@geekruchika  I am facing the exact same issue  with FlickVideoManager._changeVideo function.
The Exception Handler points to this line of code  in video_manager.dart file 
` if (autoPlay && ModalRoute.of(_flickManager._context!)!.isCurrent) {
      // Start playing the video.
      _flickManager.flickControlManager!.play();
    }`

Attaching screenshot for more clearity

![Screenshot 2021-05-21 at 10 21 31 AM](https://user-images.githubusercontent.com/7473761/119083820-53a46500-ba1e-11eb-8278-47342459b637.png)

**Comment by mkranus** [comment]
I solved this issue by setting `autoPlay` and `autoInitialize` to `false`

**Comment by mrinaljain** [comment]
Doesn't work for me , also I need to auto play my videos

**Comment by geekruchika** [comment]
Hope the above fix solves this issue.  Please free to open if still exist.

**Comment by Hwan-seok** [comment]
@geekruchika Why is this issue closed though the PR is not merged?

**Comment by Hwan-seok** [comment]
This happens frequently yet, I think any code is changed since this issue. 
We should autoinitialize and autoplay feature and also not encountering null check operator error.

**Comment by ayberkcal** [comment]
I'va faced same issue. And solved with this issue by setting autoPlay and autoInitialize to false. I think there is a some hidden bug :/

**Comment by DanieleErcoles** [comment]
we had the same problem and solved it by registering the context right after the declaration.

`
flickManager = FlickManager(
      videoPlayerController:
          VideoPlayerController.network("url"),
    )..registerContext(context);
`
