### ISSUE TITLE
What do I need to do if I want to display subtitles?

### ISSUE THREAD

**Issue by mploigt** [GeekyAnts/flick-video-player#91]
I need to display the videos with subtitles in .srt format. The video_player supports this. Do you plan to integrate this functionality too?

**Comment by geekruchika** [comment]
yes, we are working on it.

**Comment by geekruchika** [comment]
Hi @mploigt 
Here you go!
Try out version 0.4.0-dev.3.

**Comment by mploigt** [comment]
Thank you! I will try this out right now.
