### ISSUE TITLE
Video player on flutter web looses it's visibility after  switching  to fullscreen and then exiting fullscreen.

### ISSUE THREAD

**Issue by mrinaljain** [GeekyAnts/flick-video-player#92]
Im using this plug-in for a web app and I'm facing the issue

Video player on flutter web looses it's visibility after  switching  to fullscreen and then exiting fullscreen.

Steps to reproduce
- Choose any examples provided in the repository and build for web.
-  see that video plays normally on virtierticalcal mode.
-  now switch to full screen and video will run properly till now
-  now exit the full screen and video will disappear suddenly.

**Comment by geekruchika** [comment]
Please try this version and let us know. Still in development
https://pub.dev/packages/flick_video_player/versions/0.4.0-dev.1

**Comment by r4rinshadnk** [comment]
Video player on flutter web looses it's visibility after switching to fullscreen and then exiting fullscreen, issue not solved
