### ISSUE TITLE
Circular progress indicator color

### ISSUE THREAD

**Issue by worldofsites** [GeekyAnts/flick-video-player#95]
How to change default circular progress indicator color (blue)?
![image](https://user-images.githubusercontent.com/23352829/120947631-49969c00-c76a-11eb-8eb0-2215e7abf390.png)

**Comment by geekruchika** [comment]
You can pass your own loaders.

**Comment by worldofsites** [comment]
@geekruchika Could you please share some example?

**Comment by geekruchika** [comment]
Try these options.
![image](https://user-images.githubusercontent.com/32259133/125953926-2b2fe70d-da98-49f0-9da2-172b0f650f07.png)

**Comment by worldofsites** [comment]
@geekruchika Thanks! But it would be cool if it would be possible to pass custom buffering widget as a parameter in base implementation of FlickVideoPlayer.
If someone face with same problem, create copy from FlickPortraitControls and override bufferingChild:
```
FlickVideoPlayer(
                  flickManager: flickManager,
                  flickVideoWithControls: const FlickVideoWithControls(
                    controls: const FlickPortraitControlsCustom(),
                  ),
                )
```
And in FlickPortraitControlsCustom:
```
FlickVideoBuffer(
                  bufferingChild: <--- HERE YOUR CUSTOM BUFFERING WIDGET --->  ,
```

**Comment by adrianvintu** [comment]
The circular progress indicator is using the accent color, afaik. There were some emulators and maybe even phones that showed blue color - maybe after a flutter upgrade? Now it's back to accent color.
